#ifndef RUDO_DEFAULTS_H
#define RUDO_DEFAULTS_H

#include "rudo/common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define RUDO_APP_NAME "rudo"
#define RUDO_VERSION "0.1.0"

#define RUDO_CONFIG_FILE_NAME "config.toml"
#define RUDO_THEME_FILE_NAME "theme.toml"
#define RUDO_LEGACY_CONFIG_DIR_NAME "swiftterm"
#define RUDO_THEME_ENV_VAR "RUDO_THEME"

#define RUDO_DEFAULT_FONT_FAMILY "monospace"
#define RUDO_DEFAULT_FONT_SIZE 14.0f
#define RUDO_DEFAULT_FONT_SIZE_ADJUSTMENT 0.5f
#define RUDO_DEFAULT_BOLD_IS_BRIGHT false

#define RUDO_DEFAULT_FOREGROUND_HEX "#d4d4d4"
#define RUDO_DEFAULT_BACKGROUND_HEX "#1e1e1e"
#define RUDO_DEFAULT_CURSOR_HEX "#ffffff"
#define RUDO_DEFAULT_SELECTION_HEX "#264f78"
#define RUDO_DEFAULT_FOREGROUND_RGB 0xd4d4d4u
#define RUDO_DEFAULT_BACKGROUND_RGB 0x1e1e1eu

extern const char *const rudo_default_ansi_hex[16];

#define RUDO_DEFAULT_CURSOR_STYLE "block"
#define RUDO_DEFAULT_CURSOR_ANIMATION_LENGTH_SECS 0.150f
#define RUDO_DEFAULT_CURSOR_SHORT_ANIMATION_LENGTH_SECS 0.04f
#define RUDO_DEFAULT_CURSOR_TRAIL_SIZE 1.0f
#define RUDO_DEFAULT_CURSOR_BLINK_ENABLED false
#define RUDO_DEFAULT_CURSOR_BLINK_INTERVAL_SECS 0.6f
#define RUDO_DEFAULT_CURSOR_VFX_MODE ""
#define RUDO_DEFAULT_CURSOR_VFX_OPACITY 200.0f
#define RUDO_DEFAULT_CURSOR_VFX_PARTICLE_LIFETIME 0.5f
#define RUDO_DEFAULT_CURSOR_VFX_PARTICLE_HIGHLIGHT_LIFETIME 0.2f
#define RUDO_DEFAULT_CURSOR_VFX_PARTICLE_DENSITY 0.7f
#define RUDO_DEFAULT_CURSOR_VFX_PARTICLE_SPEED 10.0f
#define RUDO_DEFAULT_CURSOR_VFX_PARTICLE_PHASE 1.5f
#define RUDO_DEFAULT_CURSOR_VFX_PARTICLE_CURL 1.0f
#define RUDO_DEFAULT_CURSOR_SMOOTH_BLINK false
#define RUDO_DEFAULT_CURSOR_UNFOCUSED_OUTLINE_WIDTH 0.125f

#define RUDO_DEFAULT_WINDOW_PADDING_PX 0u
#define RUDO_DEFAULT_WINDOW_INITIAL_WIDTH 800u
#define RUDO_DEFAULT_WINDOW_INITIAL_HEIGHT 600u
#define RUDO_DEFAULT_WINDOW_OPACITY 1.0f

#define RUDO_DEFAULT_TERMINAL_COLS 80u
#define RUDO_DEFAULT_TERMINAL_ROWS 24u
#define RUDO_DEFAULT_TERM "xterm-256color"
#define RUDO_DEFAULT_COLORTERM "truecolor"
#define RUDO_DEFAULT_SHELL_FALLBACK "/bin/sh"
#define RUDO_DEFAULT_SCROLLBACK_LINES 10000u

#define RUDO_DEFAULT_CLIPBOARD_COPY_COMMAND "wl-copy"
#define RUDO_DEFAULT_CLIPBOARD_PASTE_COMMAND "wl-paste"
#define RUDO_DEFAULT_PRIMARY_COPY_COMMAND "wl-copy"
#define RUDO_DEFAULT_PRIMARY_PASTE_COMMAND "wl-paste"

#ifdef __cplusplus
}
#endif

#endif
