#include "rudo/core.h"
#include "rudo/defaults.h"

#include <errno.h>
#include <ctype.h>
#include <fcntl.h>
#include <math.h>
#include <spawn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/poll.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#define PTY_READ_BUFFER_SIZE 131072u
#define MAX_PTY_BYTES_PER_TICK (PTY_READ_BUFFER_SIZE * 8u)
#define SCROLL_MULTIPLIER 3u
#define DEFAULT_CELL_WIDTH 9.0f
#define DEFAULT_CELL_HEIGHT 18.0f
#define CLIPBOARD_MAX_BYTES (16u * 1024u * 1024u)
#define CLIPBOARD_TIMEOUT_MS 2000
#define SYNC_UPDATE_WATCHDOG_SECONDS 0.15

struct rudo_core_app {
    rudo_grid grid;
    rudo_cursor_renderer *cursor_renderer;
    rudo_damage_tracker damage;
    rudo_terminal_parser parser;
    rudo_pty *pty;
    rudo_selection selection;
    rudo_config config;
    rudo_theme theme;
    struct timespec last_frame;
    rudo_modifiers modifiers;
    char *last_title;
    float cell_w, cell_h;
    float offset_x, offset_y;
    bool title_changed, theme_changed, mouse_pressed, needs_redraw, pty_dead, pty_exit_status_ready;
    bool sync_active_last_tick;
    struct timespec sync_begin;
    int pty_exit_status;
    rudo_mouse_button mouse_button;
    double last_mouse_x, last_mouse_y, scroll_accumulator;
    char **command;
    size_t command_len;
};

static void timespec_now(struct timespec *ts) { clock_gettime(CLOCK_MONOTONIC, ts); }
static void timespec_sub_clamped(struct timespec *out, const struct timespec *a, const struct timespec *b) { time_t sec; long nsec; if (!out || !a || !b) return; sec = a->tv_sec - b->tv_sec; nsec = a->tv_nsec - b->tv_nsec; if (nsec < 0) { --sec; nsec += 1000000000L; } if (sec < 0) { out->tv_sec = 0; out->tv_nsec = 0; return; } out->tv_sec = sec; out->tv_nsec = nsec; }
static float timespec_elapsed_secs(const struct timespec *from) { struct timespec now; timespec_now(&now); return (float)((double)(now.tv_sec - from->tv_sec) + (double)(now.tv_nsec - from->tv_nsec) / 1e9); }
static double timespec_since_secs(const struct timespec *from) { return (double)timespec_elapsed_secs(from); }
static void apply_cli_overrides(rudo_config *cfg, const rudo_cli_args *cli) { if (cli->app_id) { free(cfg->window.app_id); cfg->window.app_id = rudo_strdup(cli->app_id); } if (cli->title) { free(cfg->window.title); cfg->window.title = rudo_strdup(cli->title); } }
static void build_cursor_renderer(rudo_core_app *app) { rudo_cursor_vfx_settings vfx; app->cursor_renderer = rudo_cursor_renderer_new(); rudo_cursor_renderer_set_animation_length(app->cursor_renderer, app->config.cursor.animation_length); rudo_cursor_renderer_set_short_animation_length(app->cursor_renderer, app->config.cursor.short_animation_length); rudo_cursor_renderer_set_trail_size(app->cursor_renderer, app->config.cursor.trail_size); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, app->config.cursor.blink); rudo_cursor_renderer_set_blink_interval(app->cursor_renderer, app->config.cursor.blink_interval); rudo_cursor_vfx_settings_default(&vfx); vfx.mode_count = rudo_cursor_vfx_modes_parse(app->config.cursor.vfx_mode, vfx.modes, RUDO_ARRAY_LEN(vfx.modes)); vfx.opacity = app->config.cursor.vfx_opacity; vfx.particle_lifetime = app->config.cursor.vfx_particle_lifetime; vfx.particle_highlight_lifetime = app->config.cursor.vfx_particle_highlight_lifetime; vfx.particle_density = app->config.cursor.vfx_particle_density; vfx.particle_speed = app->config.cursor.vfx_particle_speed; vfx.particle_phase = app->config.cursor.vfx_particle_phase; vfx.particle_curl = app->config.cursor.vfx_particle_curl; rudo_cursor_renderer_set_vfx_settings(app->cursor_renderer, &vfx); rudo_cursor_renderer_set_smooth_blink(app->cursor_renderer, app->config.cursor.smooth_blink); rudo_cursor_renderer_set_unfocused_outline_width(app->cursor_renderer, app->config.cursor.unfocused_outline_width); if (rudo_streq_nocase(app->config.cursor.style, "beam") || rudo_streq_nocase(app->config.cursor.style, "bar") || rudo_streq_nocase(app->config.cursor.style, "vertical")) rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_BEAM); else if (rudo_streq_nocase(app->config.cursor.style, "underline") || rudo_streq_nocase(app->config.cursor.style, "horizontal")) rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_UNDERLINE); else rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_BLOCK); }
static void app_write_pty(rudo_core_app *app, const void *buf, size_t len) { if (app->pty) rudo_pty_write(app->pty, buf, len); }
static void app_paste_text(rudo_core_app *app, const char *text) { if (rudo_terminal_parser_bracketed_paste(&app->parser)) { app_write_pty(app, "\033[200~", 6); app_write_pty(app, text, strlen(text)); app_write_pty(app, "\033[201~", 6); } else app_write_pty(app, text, strlen(text)); }
static void pixel_to_grid(const rudo_core_app *app, double x, double y, size_t *col, size_t *row) { float cw = (isfinite(app->cell_w) && app->cell_w > 0.0f) ? app->cell_w : DEFAULT_CELL_WIDTH, ch = (isfinite(app->cell_h) && app->cell_h > 0.0f) ? app->cell_h : DEFAULT_CELL_HEIGHT; size_t c = (size_t)RUDO_MAX(floor((x - app->offset_x) / cw), 0.0), r = (size_t)RUDO_MAX(floor((y - app->offset_y) / ch), 0.0); if (app->grid.cols) c = RUDO_MIN(c, app->grid.cols - 1u); if (app->grid.rows) r = RUDO_MIN(r, app->grid.rows - 1u); if (col) *col = c; if (row) *row = r; }
static void mark_selection_snapshot(rudo_core_app *app, rudo_selection_state state, rudo_grid_point start, rudo_grid_point end) { size_t a,b; if (state == RUDO_SELECTION_NONE || !app->grid.rows) return; a = RUDO_MIN(start.row, end.row); b = RUDO_MIN(RUDO_MAX(start.row, end.row), app->grid.rows - 1u); rudo_damage_mark_rows(&app->damage, a, b); }
static void mark_selection_change(rudo_core_app *app, rudo_selection_state bs, rudo_grid_point bp0, rudo_grid_point bp1, rudo_selection_state as, rudo_grid_point ap0, rudo_grid_point ap1) { mark_selection_snapshot(app, bs, bp0, bp1); mark_selection_snapshot(app, as, ap0, ap1); }
static bool clipboard_pipe_command(const char *cmd, char *const argv[], const char *text) { pid_t pid; int pipefd[2]; struct pollfd pfd; size_t len = strlen(text), off = 0; if (len > CLIPBOARD_MAX_BYTES) len = CLIPBOARD_MAX_BYTES; if (pipe(pipefd) != 0) return false; pid = fork(); if (pid == 0) { dup2(pipefd[0], 0); close(pipefd[0]); close(pipefd[1]); int devnull = open("/dev/null", O_WRONLY); if (devnull >= 0) { dup2(devnull, 1); dup2(devnull, 2); if (devnull > 2) close(devnull); } execvp(cmd, argv); _exit(127); } close(pipefd[0]); pfd.fd = pipefd[1]; pfd.events = POLLOUT; while (off < len) { if (poll(&pfd, 1, CLIPBOARD_TIMEOUT_MS) <= 0) break; ssize_t n = write(pipefd[1], text + off, len - off); if (n > 0) off += (size_t)n; else if (n < 0 && errno != EINTR) break; } close(pipefd[1]); waitpid(pid, NULL, 0); return off == len; }
static char *clipboard_read_command(const char *cmd, char *const argv[]) { pid_t pid; int pipefd[2]; rudo_str out; char buf[4096]; ssize_t n; struct pollfd pfd; if (pipe(pipefd) != 0) return NULL; rudo_str_init(&out); pid = fork(); if (pid == 0) { dup2(pipefd[1], 1); close(pipefd[0]); close(pipefd[1]); int devnull = open("/dev/null", O_WRONLY); if (devnull >= 0) { dup2(devnull, 2); if (devnull > 2) close(devnull); } execvp(cmd, argv); _exit(127); } close(pipefd[1]); pfd.fd = pipefd[0]; pfd.events = POLLIN; while (out.len < CLIPBOARD_MAX_BYTES) { int rc = poll(&pfd, 1, CLIPBOARD_TIMEOUT_MS); if (rc <= 0) break; n = read(pipefd[0], buf, sizeof(buf)); if (n > 0) rudo_str_append_mem(&out, buf, (size_t)n); else break; } close(pipefd[0]); waitpid(pid, NULL, 0); return out.data ? rudo_str_take(&out) : NULL; }
bool rudo_clipboard_set(const char *text) { char *const argv[] = { (char *)RUDO_DEFAULT_CLIPBOARD_COPY_COMMAND, NULL }; return clipboard_pipe_command(argv[0], argv, text ? text : ""); }
char *rudo_clipboard_get(void) { char *const argv[] = { (char *)RUDO_DEFAULT_CLIPBOARD_PASTE_COMMAND, (char *)"--no-newline", NULL }; return clipboard_read_command(argv[0], argv); }
bool rudo_primary_set(const char *text) { char *const argv[] = { (char *)RUDO_DEFAULT_PRIMARY_COPY_COMMAND, (char *)"--primary", NULL }; return clipboard_pipe_command(argv[0], argv, text ? text : ""); }
char *rudo_primary_get(void) { char *const argv[] = { (char *)RUDO_DEFAULT_PRIMARY_PASTE_COMMAND, (char *)"--primary", (char *)"--no-newline", NULL }; return clipboard_read_command(argv[0], argv); }
rudo_core_app *rudo_core_app_new(const rudo_cli_args *cli) { rudo_core_app *app = rudo_calloc(1, sizeof(*app)); rudo_config_load(&app->config); if (cli) apply_cli_overrides(&app->config, cli); if (!rudo_theme_load(&app->theme)) rudo_theme_from_config_colors(&app->theme, &app->config.colors); rudo_grid_init(&app->grid, RUDO_MAX(app->config.terminal.cols, 2u), RUDO_MAX(app->config.terminal.rows, 2u), app->config.scrollback.lines); rudo_damage_init(&app->damage, app->grid.rows); rudo_terminal_parser_init(&app->parser, &app->theme); rudo_selection_init(&app->selection); build_cursor_renderer(app); app->cell_w = DEFAULT_CELL_WIDTH; app->cell_h = DEFAULT_CELL_HEIGHT; app->needs_redraw = true; app->mouse_button.kind = RUDO_MOUSE_BUTTON_LEFT; timespec_now(&app->last_frame); app->sync_active_last_tick = false; app->sync_begin = app->last_frame; if (cli && cli->command_len) { size_t i; app->command = rudo_calloc(cli->command_len, sizeof(*app->command)); app->command_len = cli->command_len; for (i = 0; i < cli->command_len; ++i) app->command[i] = rudo_strdup(cli->command[i]); } return app; }
void rudo_core_app_free(rudo_core_app *app) { size_t i; if (!app) return; rudo_pty_free(app->pty); rudo_grid_destroy(&app->grid); rudo_damage_destroy(&app->damage); rudo_terminal_parser_destroy(&app->parser); rudo_cursor_renderer_free(app->cursor_renderer); rudo_config_destroy(&app->config); free(app->last_title); for (i = 0; i < app->command_len; ++i) free(app->command[i]); free(app->command); free(app); }
const rudo_config *rudo_core_app_config(const rudo_core_app *app) { return &app->config; }
const char *rudo_core_app_app_id(const rudo_core_app *app) { return app->config.window.app_id; }
const char *rudo_core_app_title(const rudo_core_app *app) { return app->last_title ? app->last_title : app->config.window.title; }
const rudo_theme *rudo_core_app_theme(const rudo_core_app *app) { return &app->theme; }
const rudo_grid *rudo_core_app_grid(const rudo_core_app *app) { return &app->grid; }
const rudo_selection *rudo_core_app_selection(const rudo_core_app *app) { return &app->selection; }
const rudo_damage_tracker *rudo_core_app_damage(const rudo_core_app *app) { return &app->damage; }
rudo_damage_tracker *rudo_core_app_damage_mut(rudo_core_app *app) { return &app->damage; }
const rudo_cursor_renderer *rudo_core_app_cursor_renderer(const rudo_core_app *app) { return app->cursor_renderer; }
rudo_modifiers rudo_core_app_modifiers(const rudo_core_app *app) { return app->modifiers; }
bool rudo_core_app_pty_exited(const rudo_core_app *app) { return app->pty_dead; }
bool rudo_core_app_poll_pty_exit(rudo_core_app *app) {
    if (!app || !app->pty) return app && app->pty_dead;
    if (rudo_pty_take_exit_status(app->pty, &app->pty_exit_status)) {
        app->pty_dead = true;
        app->pty_exit_status_ready = true;
    }
    return app->pty_dead;
}
bool rudo_core_app_take_pty_exit_status(rudo_core_app *app, int *status) {
    if (!app) return false;
    rudo_core_app_poll_pty_exit(app);
    if (!app->pty_exit_status_ready) return false;
    if (status) *status = app->pty_exit_status;
    return true;
}
int rudo_core_app_pty_raw_fd(const rudo_core_app *app) { return app->pty ? rudo_pty_master_fd(app->pty) : -1; }
int rudo_exit_code_from_wait_status(int status) {
    if (WIFEXITED(status)) return WEXITSTATUS(status);
    if (WIFSIGNALED(status)) return 128 + WTERMSIG(status);
    return 1;
}
void rudo_core_app_clear_damage(rudo_core_app *app) { rudo_damage_clear(&app->damage); }
void rudo_core_app_set_cell_size(rudo_core_app *app, float cell_w, float cell_h) { if (cell_w > 0.0f) app->cell_w = cell_w; if (cell_h > 0.0f) app->cell_h = cell_h; }
void rudo_core_app_set_grid_offset(rudo_core_app *app, float offset_x, float offset_y) { app->offset_x = offset_x; app->offset_y = offset_y; }
void rudo_core_app_set_modifiers(rudo_core_app *app, rudo_modifiers modifiers) { app->modifiers = modifiers; }
void rudo_core_app_init_terminal(rudo_core_app *app, size_t cols, size_t rows) { rudo_pty_spawn_config spawn; cols = RUDO_MAX(cols, 2u); rows = RUDO_MAX(rows, 2u); rudo_grid_reset(&app->grid, cols, rows, app->config.scrollback.lines); rudo_damage_resize(&app->damage, rows); rudo_pty_free(app->pty); app->pty_exit_status_ready = false; app->pty_exit_status = 0; app->sync_active_last_tick = false; timespec_now(&app->sync_begin); spawn.term = app->config.terminal.term; spawn.colorterm = app->config.terminal.colorterm; spawn.shell_fallback = app->config.terminal.shell_fallback; spawn.command = app->command; spawn.command_len = app->command_len; app->pty = rudo_pty_spawn((uint16_t)cols, (uint16_t)rows, &spawn); app->pty_dead = app->pty == NULL; app->needs_redraw = true; }
void rudo_core_app_handle_key_event(rudo_core_app *app, const rudo_key_event *event) { const char *text; bool app_cursor; if (!event || !event->pressed || !app->pty) return; if (rudo_keybindings_matches(&app->config.keybindings, RUDO_LOCAL_ACTION_COPY, event, app->modifiers)) { if (rudo_selection_has_selection(&app->selection)) { char *s = rudo_selection_selected_text(&app->selection, &app->grid); rudo_clipboard_set(s); free(s); } return; } if (rudo_keybindings_matches(&app->config.keybindings, RUDO_LOCAL_ACTION_PASTE, event, app->modifiers)) { char *s = rudo_clipboard_get(); if (s) { app_paste_text(app, s); free(s); } return; } if (app->modifiers.ctrl && event->key.kind == RUDO_KEY_TEXT && event->key.text && event->key.text[0] && isalpha((unsigned char)event->key.text[0])) { uint8_t code = (uint8_t)(tolower((unsigned char)event->key.text[0]) - 'a' + 1); app_write_pty(app, &code, 1); return; } app_cursor = rudo_terminal_parser_application_cursor_keys(&app->parser); switch (event->key.kind) { case RUDO_KEY_ENTER: app_write_pty(app, "\r", 1); break; case RUDO_KEY_BACKSPACE: app_write_pty(app, "\177", 1); break; case RUDO_KEY_ESCAPE: app_write_pty(app, "\033", 1); break; case RUDO_KEY_TAB: app_write_pty(app, "\t", 1); break; case RUDO_KEY_SPACE: app_write_pty(app, " ", 1); break; case RUDO_KEY_ARROW_UP: app_write_pty(app, app_cursor ? "\033OA" : "\033[A", 3); break; case RUDO_KEY_ARROW_DOWN: app_write_pty(app, app_cursor ? "\033OB" : "\033[B", 3); break; case RUDO_KEY_ARROW_RIGHT: app_write_pty(app, app_cursor ? "\033OC" : "\033[C", 3); break; case RUDO_KEY_ARROW_LEFT: app_write_pty(app, app_cursor ? "\033OD" : "\033[D", 3); break; case RUDO_KEY_HOME: app_write_pty(app, app_cursor ? "\033OH" : "\033[H", 3); break; case RUDO_KEY_END: app_write_pty(app, app_cursor ? "\033OF" : "\033[F", 3); break; case RUDO_KEY_PAGE_UP: app_write_pty(app, "\033[5~", 4); break; case RUDO_KEY_PAGE_DOWN: app_write_pty(app, "\033[6~", 4); break; case RUDO_KEY_DELETE: app_write_pty(app, "\033[3~", 4); break; case RUDO_KEY_INSERT: app_write_pty(app, "\033[2~", 4); break; case RUDO_KEY_FUNCTION: { static const char *fkeys[] = {"","\033OP","\033OQ","\033OR","\033OS","\033[15~","\033[17~","\033[18~","\033[19~","\033[20~","\033[21~","\033[23~","\033[24~"}; if (event->key.function < RUDO_ARRAY_LEN(fkeys) && fkeys[event->key.function][0]) app_write_pty(app, fkeys[event->key.function], strlen(fkeys[event->key.function])); } break; case RUDO_KEY_TEXT: text = event->key.text ? event->key.text : ""; app_write_pty(app, text, strlen(text)); break; default: break; } }
bool rudo_core_app_matches_local_keybinding(const rudo_core_app *app, rudo_local_action action, const rudo_key_event *event) { return rudo_keybindings_matches(&app->config.keybindings, action, event, app->modifiers); }
void rudo_core_app_handle_mouse_button(rudo_core_app *app, bool pressed, rudo_mouse_button button) { size_t col, row; char seq[64]; size_t n; rudo_selection_state bs, as; rudo_grid_point bp0, bp1, ap0, ap1; pixel_to_grid(app, app->last_mouse_x, app->last_mouse_y, &col, &row); if (rudo_mouse_state_is_active(rudo_terminal_parser_mouse_state(&app->parser)) && !app->modifiers.shift) { int btn_code = rudo_mouse_button_code(button); if (btn_code >= 0) { n = pressed ? rudo_mouse_encode_press(rudo_terminal_parser_mouse_state(&app->parser), (uint8_t)btn_code, rudo_mouse_modifier_bits(app->modifiers), (uint16_t)col, (uint16_t)row, seq) : rudo_mouse_encode_release(rudo_terminal_parser_mouse_state(&app->parser), (uint8_t)btn_code, rudo_mouse_modifier_bits(app->modifiers), (uint16_t)col, (uint16_t)row, seq); if (n) app_write_pty(app, seq, n); } app->mouse_pressed = pressed; app->mouse_button = button; return; } if (button.kind == RUDO_MOUSE_BUTTON_LEFT) { rudo_selection_snapshot(&app->selection, &bs, &bp0, &bp1); if (pressed) { app->mouse_pressed = true; app->mouse_button = button; rudo_selection_clear(&app->selection); rudo_selection_start(&app->selection, col, row); } else { app->mouse_pressed = false; rudo_selection_finish(&app->selection); if (rudo_selection_has_selection(&app->selection)) { char *s = rudo_selection_selected_text(&app->selection, &app->grid); rudo_primary_set(s); free(s); } } rudo_selection_snapshot(&app->selection, &as, &ap0, &ap1); mark_selection_change(app, bs, bp0, bp1, as, ap0, ap1); app->needs_redraw = true; } else if (button.kind == RUDO_MOUSE_BUTTON_MIDDLE && pressed) { char *s = rudo_primary_get(); if (s) { app_paste_text(app, s); free(s); } } }
void rudo_core_app_handle_mouse_move(rudo_core_app *app, double x, double y) { size_t col, row; char seq[64]; size_t n = 0; rudo_selection_state bs, as; rudo_grid_point bp0, bp1, ap0, ap1; app->last_mouse_x = x; app->last_mouse_y = y; pixel_to_grid(app, x, y, &col, &row); if (rudo_mouse_state_is_active(rudo_terminal_parser_mouse_state(&app->parser)) && !app->modifiers.shift) { if (app->mouse_pressed) { int btn = rudo_mouse_button_code(app->mouse_button); if (btn >= 0) n = rudo_mouse_encode_drag(rudo_terminal_parser_mouse_state(&app->parser), (uint8_t)btn, rudo_mouse_modifier_bits(app->modifiers), (uint16_t)col, (uint16_t)row, seq); } else n = rudo_mouse_encode_move(rudo_terminal_parser_mouse_state(&app->parser), rudo_mouse_modifier_bits(app->modifiers), (uint16_t)col, (uint16_t)row, seq); if (n) app_write_pty(app, seq, n); } else if (app->mouse_pressed) { rudo_selection_snapshot(&app->selection, &bs, &bp0, &bp1); if (app->selection.state == RUDO_SELECTION_NONE) rudo_selection_start(&app->selection, col, row); else if (app->selection.end.col != col || app->selection.end.row != row) rudo_selection_update(&app->selection, col, row); rudo_selection_snapshot(&app->selection, &as, &ap0, &ap1); mark_selection_change(app, bs, bp0, bp1, as, ap0, ap1); app->needs_redraw = true; } }
void rudo_core_app_handle_scroll_lines(rudo_core_app *app, double lines) { char seq[64]; size_t n, i, count, col, row; if (rudo_mouse_state_is_active(rudo_terminal_parser_mouse_state(&app->parser)) && !app->modifiers.shift) { pixel_to_grid(app, app->last_mouse_x, app->last_mouse_y, &col, &row); count = (size_t)RUDO_MAX(fabs(lines), 1.0); for (i = 0; i < count; ++i) { n = rudo_mouse_encode_scroll(rudo_terminal_parser_mouse_state(&app->parser), rudo_mouse_modifier_bits(app->modifiers), lines > 0.0, (uint16_t)col, (uint16_t)row, seq); if (n) app_write_pty(app, seq, n); } return; } if (fabs(lines) < 1.0) app->scroll_accumulator += lines; if (fabs(app->scroll_accumulator) >= 1.0) { lines = trunc(app->scroll_accumulator); app->scroll_accumulator -= lines; } if (lines == 0.0) return; count = (size_t)fabs(lines) * SCROLL_MULTIPLIER; if ((lines > 0.0 ? rudo_grid_scroll_view_up(&app->grid, count) : rudo_grid_scroll_view_down(&app->grid, count))) { if (rudo_selection_has_selection(&app->selection)) rudo_selection_clear(&app->selection); rudo_damage_mark_all(&app->damage); app->needs_redraw = true; } }
void rudo_core_app_handle_focus_change(rudo_core_app *app, bool focused) { if (!app) return; rudo_cursor_renderer_set_unfocused(app->cursor_renderer, !focused); app->needs_redraw = true; if (rudo_terminal_parser_focus_reporting(&app->parser)) app_write_pty(app, focused ? "\033[I" : "\033[O", 3); }
void rudo_core_app_handle_resize(rudo_core_app *app, size_t cols, size_t rows) { cols = RUDO_MAX(cols, 2u); rows = RUDO_MAX(rows, 2u); if (cols != app->grid.cols || rows != app->grid.rows) { if (rudo_selection_has_selection(&app->selection)) rudo_selection_clear(&app->selection); rudo_grid_resize(&app->grid, cols, rows); rudo_damage_resize(&app->damage, rows); if (app->pty) rudo_pty_resize(app->pty, (uint16_t)cols, (uint16_t)rows); app->needs_redraw = true; } }
static bool process_pty_output(rudo_core_app *app) { uint8_t buf[PTY_READ_BUFFER_SIZE]; bool got = false; size_t total = 0; ssize_t n = 0; while (app->pty && (n = rudo_pty_try_read(app->pty, buf, sizeof(buf))) >= 0) { if (n == 0) break; got = true; total += (size_t)n; rudo_terminal_parser_advance(&app->parser, &app->grid, &app->damage, buf, (size_t)n); if (total >= MAX_PTY_BYTES_PER_TICK) { app->needs_redraw = true; break; } } if (app->pty && rudo_pty_take_exit_status(app->pty, &app->pty_exit_status)) { app->pty_dead = true; app->pty_exit_status_ready = true; } else if (n < 0 && app->pty && rudo_pty_master_fd(app->pty) < 0) app->pty_dead = true; if (!got) return false; if (rudo_grid_is_viewing_scrollback(&app->grid)) { rudo_grid_reset_view(&app->grid); rudo_damage_mark_all(&app->damage); } { char **responses = NULL; size_t i, nr = rudo_terminal_parser_take_responses(&app->parser, &responses); for (i = 0; i < nr; ++i) { app_write_pty(app, responses[i], strlen(responses[i])); free(responses[i]); } free(responses); } if (rudo_terminal_parser_take_theme_changed(&app->parser)) { app->theme = *rudo_terminal_parser_theme(&app->parser); app->theme_changed = true; rudo_damage_mark_all(&app->damage); app->needs_redraw = true; } { bool has_shape = false; int shape = rudo_terminal_parser_take_cursor_shape_request(&app->parser, &has_shape); if (has_shape) { switch (shape) { case 2: rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_BLOCK); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, false); break; case 3: rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_UNDERLINE); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, true); break; case 4: rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_UNDERLINE); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, false); break; case 5: rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_BEAM); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, true); break; case 6: rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_BEAM); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, false); break; default: rudo_cursor_renderer_set_shape(app->cursor_renderer, RUDO_CURSOR_SHAPE_BLOCK); rudo_cursor_renderer_set_blink_enabled(app->cursor_renderer, true); break; } app->needs_redraw = true; } } { const char *title = rudo_terminal_parser_title(&app->parser); if ((title && !app->last_title) || (title && app->last_title && strcmp(title, app->last_title) != 0) || (!title && app->last_title)) { free(app->last_title); app->last_title = title ? rudo_strdup(title) : NULL; app->title_changed = true; } } return true; }
rudo_tick_result rudo_core_app_tick(rudo_core_app *app) { size_t col, row; float dt; rudo_cursor_tick ct; rudo_tick_result out; bool sync_active_after_io, force_redraw = false, watchdog_expired = false; dt = timespec_elapsed_secs(&app->last_frame); timespec_now(&app->last_frame); rudo_core_app_poll_pty_exit(app); process_pty_output(app); sync_active_after_io = rudo_terminal_parser_synchronized_output(&app->parser); if (sync_active_after_io && !app->sync_active_last_tick) timespec_now(&app->sync_begin); if (app->sync_active_last_tick && !sync_active_after_io) force_redraw = true; if (sync_active_after_io && timespec_since_secs(&app->sync_begin) >= SYNC_UPDATE_WATCHDOG_SECONDS) watchdog_expired = true; rudo_grid_cursor_position(&app->grid, &col, &row); ct = rudo_cursor_renderer_tick(app->cursor_renderer, (float)col, (float)row, dt); out.redraw_requested = force_redraw || app->needs_redraw || rudo_damage_has_damage(&app->damage) || ct.needs_redraw || app->theme_changed; if (sync_active_after_io && !watchdog_expired) out.redraw_requested = false; out.animating = ct.animating; app->sync_active_last_tick = sync_active_after_io; app->needs_redraw = false; return out; }
bool rudo_core_app_next_wakeup(const rudo_core_app *app, struct timespec *out_duration) { struct timespec now, elapsed; if (!app || !out_duration) return false; timespec_now(&now); timespec_sub_clamped(&elapsed, &now, &app->last_frame); return rudo_cursor_renderer_next_wakeup(app->cursor_renderer, &elapsed, out_duration); }
bool rudo_core_app_cursor_wakeup_due(const rudo_core_app *app) { struct timespec ts; return rudo_core_app_next_wakeup(app, &ts) && ts.tv_sec == 0 && ts.tv_nsec == 0; }
bool rudo_core_app_take_title_changed(rudo_core_app *app) { bool v = app->title_changed; app->title_changed = false; return v; }
bool rudo_core_app_take_theme_changed(rudo_core_app *app) { bool v = app->theme_changed; app->theme_changed = false; return v; }
void rudo_core_app_build_render_grid(const rudo_core_app *app, rudo_render_grid *out, rudo_render_cell *cells, size_t cell_count) { rudo_grid_point sel_start = {0,0}, sel_end = {0,0}; size_t last_col, last_row; memset(out, 0, sizeof(*out)); if (!app || !out || !cells || cell_count < app->grid.cols * app->grid.rows) return; rudo_grid_build_render_cells(&app->grid, cells); out->cells = cells; out->cell_count = app->grid.cols * app->grid.rows; out->cols = app->grid.cols; out->rows = app->grid.rows; out->cursor_col = app->grid.cursor_col; out->cursor_row = app->grid.cursor_row; out->cursor_visible = app->grid.cursor_visible; out->viewing_scrollback = rudo_grid_is_viewing_scrollback(&app->grid); out->has_selection = rudo_selection_has_selection(&app->selection) && app->grid.cols && app->grid.rows; if (out->has_selection) { last_col = app->grid.cols - 1u; last_row = app->grid.rows - 1u; sel_start = app->selection.start; sel_end = app->selection.end; sel_start.col = RUDO_MIN(sel_start.col, last_col); sel_start.row = RUDO_MIN(sel_start.row, last_row); sel_end.col = RUDO_MIN(sel_end.col, last_col); sel_end.row = RUDO_MIN(sel_end.row, last_row); if (sel_start.row > sel_end.row || (sel_start.row == sel_end.row && sel_start.col > sel_end.col)) { rudo_grid_point tmp = sel_start; sel_start = sel_end; sel_end = tmp; } if (sel_start.col == sel_end.col && sel_start.row == sel_end.row) out->has_selection = false; else { out->selection_start_col = sel_start.col; out->selection_start_row = sel_start.row; out->selection_end_col = sel_end.col; out->selection_end_row = sel_end.row; } } }
