#include "rudo/render.h"
#include <math.h>
#include <string.h>
#include <strings.h>

typedef struct { uint64_t state, inc; } rng_state;
typedef enum { H_SONIC_BOOM, H_RIPPLE, H_WIREFRAME } highlight_kind;
typedef enum { T_RAILGUN, T_TORPEDO, T_PIXIE_DUST } trail_kind;
typedef struct { float t, cx, cy; highlight_kind kind; } point_highlight;
typedef struct { float x, y, sx, sy, rotation_speed, lifetime; } particle_data;
typedef struct { particle_data *particles; size_t len, cap; float prev_x, prev_y; trail_kind kind; rng_state rng; float count_reminder; } particle_trail;
typedef struct rudo_cursor_vfx_state { rudo_cursor_vfx_settings settings; point_highlight highlights[8]; size_t highlight_count; particle_trail trails[8]; size_t trail_count; } rudo_cursor_vfx_state;
static float ease_in_quad(float t) { return t * t; } static float lerp1(float a, float b, float t) { return a + (b - a) * t; } static float ease(float s, float e, float t) { return lerp1(s, e, ease_in_quad(t)); }
static uint32_t rng_next(rng_state *r) { uint64_t old = r->state; uint32_t rot = (uint32_t)(old >> 59), xsh = (uint32_t)(((old >> 18) ^ old) >> 27); r->state = old * 6364136223846793005ull + r->inc; return xsh >> rot | xsh << ((-(int)rot) & 31); }
static float rng_f32(rng_state *r) { return (float)((double)rng_next(r) / 4294967296.0); }
static void normalize2(float *x, float *y) { float len = sqrtf((*x) * (*x) + (*y) * (*y)); if (len < 1e-6f) { *x = 0.0f; *y = 0.0f; } else { *x /= len; *y /= len; } }
static void rng_dir_normalized(rng_state *r, float *x, float *y) { *x = rng_f32(r) * 2.0f - 1.0f; *y = rng_f32(r) * 2.0f - 1.0f; normalize2(x, y); if (fabsf(*x) < 1e-6f && fabsf(*y) < 1e-6f) { *x = 1.0f; *y = 0.0f; } }
static void rotate_vec(float vx, float vy, float rot, float *ox, float *oy) { float s = sinf(rot), c = cosf(rot); *ox = vx * c - vy * s; *oy = vx * s + vy * c; }
static float vec_length(float x, float y) { return sqrtf(x*x + y*y); }
static int trail_reserve(particle_trail *t, size_t need) { particle_data *np; size_t nc = t->cap ? t->cap : 32u; if (need <= t->cap) return 1; while (nc < need) nc *= 2u; np = (particle_data *)realloc(t->particles, nc * sizeof(*t->particles)); if (!np) return 0; t->particles = np; t->cap = nc; return 1; }
void rudo_cursor_vfx_settings_default(rudo_cursor_vfx_settings *out) { if (!out) return; memset(out, 0, sizeof(*out)); out->opacity = RUDO_DEFAULT_CURSOR_VFX_OPACITY; out->particle_lifetime = RUDO_DEFAULT_CURSOR_VFX_PARTICLE_LIFETIME; out->particle_highlight_lifetime = RUDO_DEFAULT_CURSOR_VFX_PARTICLE_HIGHLIGHT_LIFETIME; out->particle_density = RUDO_DEFAULT_CURSOR_VFX_PARTICLE_DENSITY; out->particle_speed = RUDO_DEFAULT_CURSOR_VFX_PARTICLE_SPEED; out->particle_phase = RUDO_DEFAULT_CURSOR_VFX_PARTICLE_PHASE; out->particle_curl = RUDO_DEFAULT_CURSOR_VFX_PARTICLE_CURL; }
rudo_cursor_vfx_mode rudo_cursor_vfx_mode_parse(const char *s) { if (!s) return RUDO_CURSOR_VFX_DISABLED; if (!strcasecmp(s, "railgun")) return RUDO_CURSOR_VFX_RAILGUN; if (!strcasecmp(s, "torpedo")) return RUDO_CURSOR_VFX_TORPEDO; if (!strcasecmp(s, "pixiedust") || !strcasecmp(s, "pixie_dust")) return RUDO_CURSOR_VFX_PIXIE_DUST; if (!strcasecmp(s, "sonicboom") || !strcasecmp(s, "sonic_boom")) return RUDO_CURSOR_VFX_SONIC_BOOM; if (!strcasecmp(s, "ripple")) return RUDO_CURSOR_VFX_RIPPLE; if (!strcasecmp(s, "wireframe")) return RUDO_CURSOR_VFX_WIREFRAME; return RUDO_CURSOR_VFX_DISABLED; }
size_t rudo_cursor_vfx_modes_parse(const char *s, uint32_t *out_modes, size_t out_cap) { size_t n = 0; const char *p = s ? s : ""; while (*p) { const char *q = strchr(p, ','); char tmp[64]; size_t len = q ? (size_t)(q - p) : strlen(p); while (len && (*p == ' ' || *p == '\t')) { ++p; --len; } while (len && (p[len - 1] == ' ' || p[len - 1] == '\t')) --len; if (len && len < sizeof(tmp)) { rudo_cursor_vfx_mode m; memcpy(tmp, p, len); tmp[len] = 0; m = rudo_cursor_vfx_mode_parse(tmp); if (m != RUDO_CURSOR_VFX_DISABLED && n < out_cap) out_modes[n++] = (uint32_t)m; } if (!q) break; p = q + 1; } return n; }
static void build_effects(struct rudo_cursor_vfx_state *v) { size_t i; v->highlight_count = v->trail_count = 0; for (i = 0; i < v->settings.mode_count; ++i) switch ((rudo_cursor_vfx_mode)v->settings.modes[i]) { case RUDO_CURSOR_VFX_RAILGUN: v->trails[v->trail_count++] = (particle_trail){ .prev_x = 0.0f, .prev_y = 0.0f, .kind = T_RAILGUN, .rng = { 0x853C49E6748FEA9Bull, (0xDA3E39CB94B95BDBull << 1) | 1ull } }; break; case RUDO_CURSOR_VFX_TORPEDO: v->trails[v->trail_count++] = (particle_trail){ .prev_x = 0.0f, .prev_y = 0.0f, .kind = T_TORPEDO, .rng = { 0x853C49E6748FEA9Bull, (0xDA3E39CB94B95BDBull << 1) | 1ull } }; break; case RUDO_CURSOR_VFX_PIXIE_DUST: v->trails[v->trail_count++] = (particle_trail){ .prev_x = 0.0f, .prev_y = 0.0f, .kind = T_PIXIE_DUST, .rng = { 0x853C49E6748FEA9Bull, (0xDA3E39CB94B95BDBull << 1) | 1ull } }; break; case RUDO_CURSOR_VFX_SONIC_BOOM: v->highlights[v->highlight_count++] = (point_highlight){ 1.0f, 0.0f, 0.0f, H_SONIC_BOOM }; break; case RUDO_CURSOR_VFX_RIPPLE: v->highlights[v->highlight_count++] = (point_highlight){ 1.0f, 0.0f, 0.0f, H_RIPPLE }; break; case RUDO_CURSOR_VFX_WIREFRAME: v->highlights[v->highlight_count++] = (point_highlight){ 1.0f, 0.0f, 0.0f, H_WIREFRAME }; break; default: break; } }
rudo_cursor_vfx_state *rudo_cursor_vfx_new(const rudo_cursor_vfx_settings *settings) { rudo_cursor_vfx_state *v = (rudo_cursor_vfx_state *)calloc(1, sizeof(*v)); if (!v) return NULL; if (settings) v->settings = *settings; else rudo_cursor_vfx_settings_default(&v->settings); build_effects(v); return v; }
void rudo_cursor_vfx_free(rudo_cursor_vfx_state *v) { size_t i; if (!v) return; for (i = 0; i < v->trail_count; ++i) free(v->trails[i].particles); free(v); }
void rudo_cursor_vfx_set_settings(rudo_cursor_vfx_state *v, const rudo_cursor_vfx_settings *settings) { size_t i; if (!v || !settings) return; if (v->settings.mode_count != settings->mode_count || memcmp(v->settings.modes, settings->modes, sizeof(v->settings.modes))) { for (i = 0; i < v->trail_count; ++i) free(v->trails[i].particles); memset(v->trails, 0, sizeof(v->trails)); v->settings = *settings; build_effects(v); } else v->settings = *settings; }
static bool highlight_update(point_highlight *h, const rudo_cursor_vfx_settings *s, float x, float y, float dt) { float lifetime = s->particle_highlight_lifetime; h->cx = x; h->cy = y; h->t = lifetime > 0.0f ? RUDO_MIN(1.0f, h->t + dt / lifetime) : 1.0f; return h->t < 1.0f; }
static bool trail_update(particle_trail *t, const rudo_cursor_vfx_settings *s, float dest_x, float dest_y, float dt) { size_t i = 0; while (i < t->len) { particle_data *p = &t->particles[i]; p->lifetime -= dt; if (p->lifetime <= 0.0f) t->particles[i] = t->particles[--t->len]; else { float rx, ry; p->x += p->sx * dt; p->y += p->sy * dt; rotate_vec(p->sx, p->sy, dt * p->rotation_speed, &rx, &ry); p->sx = rx; p->sy = ry; ++i; } } if (fabsf(dest_x - t->prev_x) > 1e-4f || fabsf(dest_y - t->prev_y) > 1e-4f) { float travel_x = dest_x - t->prev_x, travel_y = dest_y - t->prev_y, travel_dist = vec_length(travel_x, travel_y), f_count = travel_dist * s->particle_density + t->count_reminder; size_t count = (size_t)f_count; float prev_x = t->prev_x, prev_y = t->prev_y; t->count_reminder = f_count - (float)count; if (count && trail_reserve(t, t->len + count)) { size_t k; for (k = 0; k < count; ++k) { float tt = (float)(k + 1u) / (float)count, sx, sy, px, py, rs; particle_data *p = &t->particles[t->len++]; switch (t->kind) { case T_RAILGUN: { float phase = tt / (float)M_PI * s->particle_phase * travel_dist; sx = sinf(phase) * 2.0f * s->particle_speed; sy = cosf(phase) * 2.0f * s->particle_speed; px = prev_x + travel_x * tt; py = prev_y + travel_y * tt; rs = (float)M_PI * s->particle_curl; } break; case T_TORPEDO: { float dx = travel_x, dy = travel_y, rx, ry; normalize2(&dx, &dy); rng_dir_normalized(&t->rng, &rx, &ry); rx -= dx * 1.5f; ry -= dy * 1.5f; normalize2(&rx, &ry); sx = rx * s->particle_speed; sy = ry * s->particle_speed; px = prev_x + travel_x * rng_f32(&t->rng); py = prev_y + travel_y * rng_f32(&t->rng) + 0.5f; rs = (rng_f32(&t->rng) - 0.5f) * ((float)M_PI_2) * s->particle_curl; } break; default: { float bx, by; rng_dir_normalized(&t->rng, &bx, &by); sx = bx * 0.5f * 3.0f * s->particle_speed; sy = (0.4f + fabsf(by)) * 3.0f * s->particle_speed; px = prev_x + travel_x * rng_f32(&t->rng); py = prev_y + travel_y * rng_f32(&t->rng) + 0.5f; rs = (rng_f32(&t->rng) - 0.5f) * ((float)M_PI_2) * s->particle_curl; } break; } p->x = px; p->y = py; p->sx = sx; p->sy = sy; p->rotation_speed = rs; p->lifetime = tt * s->particle_lifetime; } } t->prev_x = dest_x; t->prev_y = dest_y; } return t->len != 0; }
bool rudo_cursor_vfx_update(rudo_cursor_vfx_state *v, float cursor_x, float cursor_y, float cell_w, float cell_h, float dt) { size_t i; bool anim = false; RUDO_UNUSED(cell_w); RUDO_UNUSED(cell_h); if (!v || !v->settings.mode_count) return false; for (i = 0; i < v->highlight_count; ++i) anim |= highlight_update(&v->highlights[i], &v->settings, cursor_x, cursor_y, dt); for (i = 0; i < v->trail_count; ++i) anim |= trail_update(&v->trails[i], &v->settings, cursor_x, cursor_y, dt); return anim; }
void rudo_cursor_vfx_cursor_jumped(rudo_cursor_vfx_state *v, float x, float y) { size_t i; if (!v) return; for (i = 0; i < v->highlight_count; ++i) { v->highlights[i].t = 0.0f; v->highlights[i].cx = x; v->highlights[i].cy = y; } }
size_t rudo_cursor_vfx_count(const rudo_cursor_vfx_state *v) { size_t i, n = 0; if (!v || !v->settings.mode_count) return 0; for (i = 0; i < v->highlight_count; ++i) if (v->highlights[i].t != 1.0f) ++n; for (i = 0; i < v->trail_count; ++i) n += v->trails[i].len; return n; }
size_t rudo_cursor_vfx_collect(const rudo_cursor_vfx_state *v, rudo_cursor_particle *out, size_t cap) { size_t i, n = 0; if (!v || !out || !cap || !v->settings.mode_count) return 0; for (i = 0; i < v->highlight_count && n < cap; ++i) if (v->highlights[i].t != 1.0f) { uint8_t alpha = (uint8_t)ease(v->settings.opacity, 0.0f, v->highlights[i].t); float radius = v->highlights[i].t * 3.0f; rudo_cursor_particle_shape shape = v->highlights[i].kind == H_SONIC_BOOM ? RUDO_CURSOR_PARTICLE_FILLED_OVAL : v->highlights[i].kind == H_RIPPLE ? RUDO_CURSOR_PARTICLE_STROKED_OVAL : RUDO_CURSOR_PARTICLE_STROKED_RECT; out[n++] = (rudo_cursor_particle){ v->highlights[i].cx, v->highlights[i].cy, radius, alpha, shape, 0.2f }; }
    for (i = 0; i < v->trail_count && n < cap; ++i) { size_t j; for (j = 0; j < v->trails[i].len && n < cap; ++j) { const particle_data *p = &v->trails[i].particles[j]; float lf = p->lifetime / v->settings.particle_lifetime; uint8_t alpha = (uint8_t)(lf * v->settings.opacity); if (v->trails[i].kind == T_PIXIE_DUST) out[n++] = (rudo_cursor_particle){ p->x, p->y, 0.2f, alpha, RUDO_CURSOR_PARTICLE_FILLED_RECT, 0.0f }; else out[n++] = (rudo_cursor_particle){ p->x, p->y, 0.5f * lf, alpha, RUDO_CURSOR_PARTICLE_STROKED_OVAL, 0.2f }; } }
    return n; }
