#define _GNU_SOURCE
#include "rudo/render.h"
#include <ctype.h>
#include <dirent.h>
#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <strings.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

#define ATLAS_WIDTH 1024u
#define ATLAS_HEIGHT 1024u
#define ASCII_RANGE 95u
#define ASCII_CACHE_LEN (ASCII_RANGE * 4u)
#define FREETYPE_FIXED_POINT_SCALE 64.0f
#define FALLBACK_BASELINE_RATIO 0.8f
#define FONT_PLAN_CACHE_DIR "font-plans-v1"
#define FONT_SLOT_UNRESOLVED 0
#define FONT_SLOT_READY 1
#define FONT_SLOT_FAILED 2


typedef struct { rudo_glyph_info glyph; uint32_t ch; uint8_t style; uint8_t used; } GlyphCacheEntry;

typedef struct { void *face; char *path; } FtFont;

struct rudo_font_atlas {
    FtFont regular, bold, italic, bold_italic;
    int bold_state, italic_state, bold_italic_state;
    FtFont *fallback_fonts; size_t fallback_font_len, fallback_font_cap;
    char **fallback_paths; size_t fallback_path_len, fallback_path_cap, next_fallback_path;
    int fallback_paths_resolved;
    char *request;
    float font_size, cell_width, cell_height, baseline;
    uint8_t *atlas_data;
    GlyphCacheEntry *cache; size_t cache_len, cache_cap;
    unsigned current_x, current_y, row_height;
    rudo_glyph_info ascii_cache[ASCII_CACHE_LEN];
    uint8_t ascii_populated[ASCII_CACHE_LEN];
};

static rudo_glyph_info empty_glyph_info(void) { rudo_glyph_info v; memset(&v, 0, sizeof(v)); return v; }
static char *dup_string(const char *s) { return s ? rudo_strdup(s) : NULL; }
static char *dup_string_n(const char *s, size_t n) { return rudo_strndup(s, n); }
static char *trimmed_copy(const char *s) { char *copy; char *t; if (!s || !*s) return rudo_strdup(RUDO_DEFAULT_FONT_FAMILY); copy = rudo_strdup(s); if (!copy) return NULL; t = rudo_trim(copy); if (t != copy) memmove(copy, t, strlen(t) + 1u); if (!*copy) { free(copy); return rudo_strdup(RUDO_DEFAULT_FONT_FAMILY); } return copy; }
static int path_exists(const char *path) { return path && access(path, R_OK) == 0; }
static char *path_join2(const char *a, const char *b) { return rudo_path_join2(a, b); }
static char *path_join3(const char *a, const char *b, const char *c) { return rudo_path_join3(a, b, c); }
static int mkdir_p(const char *path) { char tmp[PATH_MAX]; size_t i, n; if (!path) return 0; n = strlen(path); if (!n || n >= sizeof(tmp)) return 0; memcpy(tmp, path, n + 1u); for (i = 1; i < n; ++i) if (tmp[i] == '/') { tmp[i] = 0; if (tmp[0] && mkdir(tmp, 0700) && errno != EEXIST) return 0; tmp[i] = '/'; } return mkdir(tmp, 0700) == 0 || errno == EEXIST; }
static char *cache_base_dir(void) { const char *xdg = getenv("XDG_CACHE_HOME"); const char *home; if (xdg && *xdg) return dup_string(xdg); home = getenv("HOME"); return (home && *home) ? path_join2(home, ".cache") : NULL; }
static char *sanitize_cache_key(const char *request) { const char *src = request ? request : RUDO_DEFAULT_FONT_FAMILY; size_t n = strlen(src), i, out_len = 0; int last_sep = 0; char *out = (char *)malloc((n ? n : 1u) + 1u); if (!out) return NULL; for (i = 0; i < n && out_len < 80u; ++i) { unsigned char ch = (unsigned char)src[i]; if (isalnum(ch)) { out[out_len++] = (char)tolower(ch); last_sep = 0; } else if (!last_sep) { out[out_len++] = '_'; last_sep = 1; } } while (out_len && out[out_len - 1u] == '_') --out_len; if (!out_len) { memcpy(out, "default", 8u); return out; } out[out_len] = 0; return out; }
static char *font_plan_cache_path(const char *request) { char *base = cache_base_dir(), *app_dir, *cache_dir, *key, *file_name, *path; size_t key_len; if (!base) return NULL; app_dir = path_join2(base, RUDO_APP_NAME); free(base); if (!app_dir) return NULL; cache_dir = path_join2(app_dir, FONT_PLAN_CACHE_DIR); free(app_dir); if (!cache_dir) return NULL; key = sanitize_cache_key(request); if (!key) { free(cache_dir); return NULL; } key_len = strlen(key); file_name = (char *)malloc(key_len + 5u); if (!file_name) { free(key); free(cache_dir); return NULL; } memcpy(file_name, key, key_len); memcpy(file_name + key_len, ".txt", 5u); free(key); path = path_join2(cache_dir, file_name); free(file_name); free(cache_dir); return path; }
static char *read_cached_regular_path(const char *request) { char *path = font_plan_cache_path(request), *line = NULL, *regular = NULL; size_t cap = 0; ssize_t nread; FILE *fp; if (!path) return NULL; fp = fopen(path, "r"); free(path); if (!fp) return NULL; while ((nread = getline(&line, &cap, fp)) >= 0) { char *eq, *value, *end; if (!nread) continue; eq = strchr(line, '='); if (!eq) continue; *eq = 0; if (strcmp(line, "regular")) continue; value = eq + 1; end = value + strlen(value); while (end > value && (end[-1] == '\n' || end[-1] == '\r' || isspace((unsigned char)end[-1]))) --end; while (*value && isspace((unsigned char)*value)) ++value; if (end > value) regular = dup_string_n(value, (size_t)(end - value)); break; } free(line); fclose(fp); if (!path_exists(regular)) { free(regular); return NULL; } return regular; }
static void write_cached_regular_path(const char *request, const char *regular) { char *path, *dir, *slash; FILE *fp; if (!regular || !*regular) return; path = font_plan_cache_path(request); if (!path) return; dir = dup_string(path); if (!dir) { free(path); return; } slash = strrchr(dir, '/'); if (!slash) { free(dir); free(path); return; } *slash = 0; if (!mkdir_p(dir)) { free(dir); free(path); return; } free(dir); fp = fopen(path, "w"); if (fp) { fprintf(fp, "regular=%s\n", regular); fclose(fp); } free(path); }
static int grow_array(void **ptr, size_t elem_size, size_t *cap, size_t need) { size_t new_cap; void *new_ptr; if (need <= *cap) return 1; new_cap = *cap ? *cap : 8u; while (new_cap < need) new_cap *= 2u; new_ptr = realloc(*ptr, elem_size * new_cap); if (!new_ptr) return 0; *ptr = new_ptr; *cap = new_cap; return 1; }
static int string_array_contains(char **items, size_t len, const char *value) { size_t i; for (i = 0; i < len; ++i) if (items[i] && !strcmp(items[i], value)) return 1; return 0; }
static int append_unique_string(char ***items, size_t *len, size_t *cap, const char *value) { char *copy; if (!value || !*value || string_array_contains(*items, *len, value)) return 1; if (!grow_array((void **)items, sizeof(char *), cap, *len + 1u)) return 0; copy = dup_string(value); if (!copy) return 0; (*items)[(*len)++] = copy; return 1; }
static void free_string_array(char **items, size_t len) { size_t i; if (!items) return; for (i = 0; i < len; ++i) free(items[i]); free(items); }

typedef unsigned char FcChar8; typedef int FcBool; typedef int FcResult; typedef int FcMatchKind; typedef void FcConfig; typedef void FcPattern; typedef struct { int nfont, sfont; FcPattern **fonts; } FcFontSet; typedef struct { void *lib; FcConfig *(*FcInitLoadConfigAndFonts)(void); void (*FcConfigDestroy)(FcConfig *); FcPattern *(*FcNameParse)(const FcChar8 *); void (*FcPatternDestroy)(FcPattern *); FcBool (*FcConfigSubstitute)(FcConfig *, FcPattern *, FcMatchKind); void (*FcDefaultSubstitute)(FcPattern *); FcPattern *(*FcFontMatch)(FcConfig *, FcPattern *, FcResult *); FcFontSet *(*FcFontSort)(FcConfig *, FcPattern *, FcBool, void *, FcResult *); void (*FcFontSetDestroy)(FcFontSet *); FcResult (*FcPatternGetString)(const FcPattern *, const char *, int, FcChar8 **); } FcHandle; static FcHandle g_fc; static int g_fc_state; enum { FC_TRUE = 1, FC_MATCH_PATTERN = 0, FC_RESULT_MATCH = 0, FC_RESULT_NOMATCH = 1 };
static void *dlopen_any2(const char *a, const char *b) { void *lib = dlopen(a, RTLD_NOW | RTLD_LOCAL); return lib ? lib : dlopen(b, RTLD_NOW | RTLD_LOCAL); }
static void *dlsym_required(void *lib, const char *name) { return dlsym(lib, name); }
static int ensure_fc(void) { void *lib; if (g_fc_state) return g_fc_state > 0; memset(&g_fc, 0, sizeof(g_fc)); lib = dlopen_any2("libfontconfig.so.1", "libfontconfig.so"); if (!lib) { g_fc_state = -1; return 0; } g_fc.lib = lib; g_fc.FcInitLoadConfigAndFonts = dlsym_required(lib, "FcInitLoadConfigAndFonts"); g_fc.FcConfigDestroy = dlsym_required(lib, "FcConfigDestroy"); g_fc.FcNameParse = dlsym_required(lib, "FcNameParse"); g_fc.FcPatternDestroy = dlsym_required(lib, "FcPatternDestroy"); g_fc.FcConfigSubstitute = dlsym_required(lib, "FcConfigSubstitute"); g_fc.FcDefaultSubstitute = dlsym_required(lib, "FcDefaultSubstitute"); g_fc.FcFontMatch = dlsym_required(lib, "FcFontMatch"); g_fc.FcFontSort = dlsym_required(lib, "FcFontSort"); g_fc.FcFontSetDestroy = dlsym_required(lib, "FcFontSetDestroy"); g_fc.FcPatternGetString = dlsym_required(lib, "FcPatternGetString"); if (!g_fc.FcInitLoadConfigAndFonts || !g_fc.FcConfigDestroy || !g_fc.FcNameParse || !g_fc.FcPatternDestroy || !g_fc.FcConfigSubstitute || !g_fc.FcDefaultSubstitute || !g_fc.FcFontMatch || !g_fc.FcFontSort || !g_fc.FcFontSetDestroy || !g_fc.FcPatternGetString) { dlclose(lib); memset(&g_fc, 0, sizeof(g_fc)); g_fc_state = -1; return 0; } g_fc_state = 1; return 1; }
static FcPattern *build_fontconfig_pattern(FcConfig *config, const char *pattern_str) { FcPattern *pattern = g_fc.FcNameParse((const FcChar8 *)pattern_str); if (!pattern) return NULL; g_fc.FcConfigSubstitute(config, pattern, FC_MATCH_PATTERN); g_fc.FcDefaultSubstitute(pattern); return pattern; }
static char *fontconfig_pattern_file(FcPattern *pattern) { FcChar8 *raw = NULL; char *path; if (!pattern) return NULL; if (g_fc.FcPatternGetString(pattern, "file", 0, &raw) != FC_RESULT_MATCH || !raw) return NULL; path = dup_string((const char *)raw); if (!path_exists(path)) { free(path); return NULL; } return path; }
static char *fontconfig_match_file(const char *pattern_str) { FcConfig *config; FcPattern *pattern, *matched; FcResult result = FC_RESULT_NOMATCH; char *path; if (!ensure_fc()) return NULL; config = g_fc.FcInitLoadConfigAndFonts(); if (!config) return NULL; pattern = build_fontconfig_pattern(config, pattern_str); if (!pattern) { g_fc.FcConfigDestroy(config); return NULL; } matched = g_fc.FcFontMatch(config, pattern, &result); path = matched ? fontconfig_pattern_file(matched) : NULL; if (matched) g_fc.FcPatternDestroy(matched); g_fc.FcPatternDestroy(pattern); g_fc.FcConfigDestroy(config); return path; }
static char **fontconfig_sort_files(const char *pattern_str, size_t *out_len) { FcConfig *config; FcPattern *pattern; FcFontSet *set; FcResult result = FC_RESULT_NOMATCH; char **paths = NULL; size_t len = 0, cap = 0; int i; *out_len = 0; if (!ensure_fc()) return NULL; config = g_fc.FcInitLoadConfigAndFonts(); if (!config) return NULL; pattern = build_fontconfig_pattern(config, pattern_str); if (!pattern) { g_fc.FcConfigDestroy(config); return NULL; } set = g_fc.FcFontSort(config, pattern, FC_TRUE, NULL, &result); if (set) { for (i = 0; i < set->nfont; ++i) { char *path = fontconfig_pattern_file(set->fonts[i]); if (!path) continue; if (!append_unique_string(&paths, &len, &cap, path)) { free(path); break; } free(path); } g_fc.FcFontSetDestroy(set); } g_fc.FcPatternDestroy(pattern); g_fc.FcConfigDestroy(config); *out_len = len; return paths; }

typedef int FT_Error; typedef void *FT_Library; typedef struct FT_FaceRec_ *FT_Face; typedef int32_t FT_Int32; typedef unsigned int FT_UInt; typedef unsigned long FT_ULong; typedef long FT_Long; typedef long FT_F26Dot6; typedef long FT_Pos; typedef long FT_Fixed; typedef struct { FT_Pos x; FT_Pos y; } FT_Vector; typedef struct { void *data; void *finalizer; } FT_Generic; typedef struct { FT_Pos xmin, ymin, xmax, ymax; } FT_BBox; typedef struct { unsigned int rows, width; int pitch; unsigned char *buffer; unsigned short num_grays; unsigned char pixel_mode, palette_mode; void *palette; } FT_Bitmap; typedef struct { FT_Pos width, height, horiBearingX, horiBearingY, horiAdvance, vertBearingX, vertBearingY, vertAdvance; } FT_Glyph_Metrics; typedef struct FT_GlyphSlotRec_ { FT_Library library; FT_Face face; struct FT_GlyphSlotRec_ *next; FT_UInt glyph_index; FT_Generic generic; FT_Glyph_Metrics metrics; FT_Fixed linearHoriAdvance, linearVertAdvance; FT_Vector advance; unsigned int format; FT_Bitmap bitmap; int bitmap_left, bitmap_top; } FT_GlyphSlotRec; typedef struct { unsigned short x_ppem, y_ppem; FT_Fixed x_scale, y_scale; FT_Pos ascender, descender, height, max_advance; } FT_Size_Metrics; typedef struct FT_SizeRec_ { FT_Face face; FT_Generic generic; FT_Size_Metrics metrics; } FT_SizeRec; typedef struct FT_FaceRec_ { FT_Long num_faces, face_index, face_flags, style_flags, num_glyphs; char *family_name, *style_name; int num_fixed_sizes; void *available_sizes; int num_charmaps; void *charmaps; FT_Generic generic; FT_BBox bbox; unsigned short units_per_em; short ascender, descender, height, max_advance_width, max_advance_height, underline_position, underline_thickness; FT_GlyphSlotRec *glyph; FT_SizeRec *size; } FT_FaceRec; typedef struct { void *lib; FT_Error (*Init_FreeType)(FT_Library *); FT_Error (*Done_FreeType)(FT_Library); FT_Error (*New_Face)(FT_Library, const char *, FT_Long, FT_Face *); FT_Error (*Done_Face)(FT_Face); FT_Error (*Set_Pixel_Sizes)(FT_Face, FT_UInt, FT_UInt); FT_Error (*Set_Char_Size)(FT_Face, FT_F26Dot6, FT_F26Dot6, FT_UInt, FT_UInt); FT_Error (*Load_Char)(FT_Face, FT_ULong, FT_Int32); FT_UInt (*Get_Char_Index)(FT_Face, FT_ULong); } FtHandle; static FtHandle g_ft; static FT_Library g_ft_library; static int g_ft_state; enum { FT_LOAD_DEFAULT = 0, FT_LOAD_RENDER = 1 << 2 };
static int ensure_ft(void) { void *lib; FT_Library library = NULL; if (g_ft_state) return g_ft_state > 0; memset(&g_ft, 0, sizeof(g_ft)); lib = dlopen_any2("libfreetype.so.6", "libfreetype.so"); if (!lib) { g_ft_state = -1; return 0; } g_ft.lib = lib; g_ft.Init_FreeType = dlsym_required(lib, "FT_Init_FreeType"); g_ft.Done_FreeType = dlsym_required(lib, "FT_Done_FreeType"); g_ft.New_Face = dlsym_required(lib, "FT_New_Face"); g_ft.Done_Face = dlsym_required(lib, "FT_Done_Face"); g_ft.Set_Pixel_Sizes = dlsym_required(lib, "FT_Set_Pixel_Sizes"); g_ft.Set_Char_Size = dlsym_required(lib, "FT_Set_Char_Size"); g_ft.Load_Char = dlsym_required(lib, "FT_Load_Char"); g_ft.Get_Char_Index = dlsym_required(lib, "FT_Get_Char_Index"); if (!g_ft.Init_FreeType || !g_ft.Done_FreeType || !g_ft.New_Face || !g_ft.Done_Face || !g_ft.Set_Pixel_Sizes || !g_ft.Set_Char_Size || !g_ft.Load_Char || !g_ft.Get_Char_Index) { dlclose(lib); g_ft_state = -1; return 0; } if (g_ft.Init_FreeType(&library) || !library) { dlclose(lib); g_ft_state = -1; return 0; } g_ft_library = library; g_ft_state = 1; return 1; }
static int has_font_extension(const char *name) { const char *dot = name ? strrchr(name, '.') : NULL; return dot && (!strcasecmp(dot, ".ttf") || !strcasecmp(dot, ".otf")); }
static char *find_first_font_in_dir(const char *dir_path) { DIR *dir = opendir(dir_path); struct dirent *entry; char **subdirs = NULL; size_t subdir_len = 0, subdir_cap = 0; char *found = NULL; if (!dir) return NULL; while ((entry = readdir(dir))) { char *path; struct stat st; if (!strcmp(entry->d_name, ".") || !strcmp(entry->d_name, "..")) continue; path = path_join2(dir_path, entry->d_name); if (!path) continue; if (stat(path, &st)) { free(path); continue; } if (S_ISREG(st.st_mode) && has_font_extension(entry->d_name)) { found = path; break; } if (S_ISDIR(st.st_mode)) { if (!grow_array((void **)&subdirs, sizeof(char *), &subdir_cap, subdir_len + 1u)) { free(path); continue; } subdirs[subdir_len++] = path; } else free(path); } closedir(dir); if (found) { free_string_array(subdirs, subdir_len); return found; } while (subdir_len) { char *sub = subdirs[--subdir_len]; found = find_first_font_in_dir(sub); free(sub); if (found) { free_string_array(subdirs, subdir_len); return found; } } free(subdirs); return NULL; }
static char *scan_filesystem_for_any_font(void) { static const char *const dirs[] = { "/usr/share/fonts", "/usr/local/share/fonts", "/nix/var/nix/profiles/system/sw/share/X11/fonts", "/run/current-system/sw/share/X11/fonts" }; const char *home; size_t i; char *path = NULL; for (i = 0; i < RUDO_ARRAY_LEN(dirs); ++i) { path = find_first_font_in_dir(dirs[i]); if (path) return path; } home = getenv("HOME"); if (home && *home) { char *dir = path_join3(home, ".local", "share/fonts"); if (dir) { path = find_first_font_in_dir(dir); free(dir); if (path) return path; } dir = path_join2(home, ".fonts"); if (dir) { path = find_first_font_in_dir(dir); free(dir); if (path) return path; } } return NULL; }
static char *resolve_regular_font_path(const char *request) { char *path = read_cached_regular_path(request); if (path) return path; path = fontconfig_match_file(request); if (!path && strcmp(request, RUDO_DEFAULT_FONT_FAMILY)) path = fontconfig_match_file(RUDO_DEFAULT_FONT_FAMILY); if (!path) path = scan_filesystem_for_any_font(); if (path) write_cached_regular_path(request, path); return path; }
static char *resolve_style_font_path(const char *request, const char *const *styles, size_t style_count) { size_t i; for (i = 0; i < style_count; ++i) { const char *style = styles[i]; size_t nr = strlen(request), ns = strlen(style); char *pattern = (char *)malloc(nr + 1u + ns + 1u), *path; if (!pattern) return NULL; memcpy(pattern, request, nr); pattern[nr] = ':'; memcpy(pattern + nr + 1u, style, ns + 1u); path = fontconfig_match_file(pattern); free(pattern); if (path) return path; } return NULL; }
static void ft_font_init(FtFont *font) { font->face = NULL; font->path = NULL; }
static void ft_font_drop(FtFont *font) { if (!font) return; if (font->face && ensure_ft()) g_ft.Done_Face((FT_Face)font->face); font->face = NULL; free(font->path); font->path = NULL; }
static void ft_face_set_size(FT_Face face, float size_px) { FT_F26Dot6 size_26_6; if (!face) return; if (size_px < 1.0f) size_px = 1.0f; size_26_6 = (FT_F26Dot6)(size_px * FREETYPE_FIXED_POINT_SCALE + 0.5f); if (g_ft.Set_Char_Size(face, 0, size_26_6, 72u, 72u)) g_ft.Set_Pixel_Sizes(face, 0u, (FT_UInt)(size_px + 0.5f)); }
static int ft_font_load(FtFont *font, const char *path, float size_px) { FT_Face face = NULL; char *copy; if (!ensure_ft() || !path) return 0; if (g_ft.New_Face(g_ft_library, path, 0, &face) || !face) return 0; copy = dup_string(path); if (!copy) { g_ft.Done_Face(face); return 0; } ft_face_set_size(face, size_px); font->face = face; font->path = copy; return 1; }
static int ft_font_has_glyph(const FtFont *font, uint32_t ch) { return font && font->face && ensure_ft() && g_ft.Get_Char_Index((FT_Face)font->face, (FT_ULong)ch) != 0u; }
static float ft_font_glyph_advance(FtFont *font, uint32_t ch) { FT_GlyphSlotRec *slot; if (!font || !font->face || !ensure_ft()) return 0.0f; if (g_ft.Load_Char((FT_Face)font->face, (FT_ULong)ch, FT_LOAD_DEFAULT)) return 0.0f; slot = ((FT_Face)font->face)->glyph; return slot ? (float)slot->metrics.horiAdvance / FREETYPE_FIXED_POINT_SCALE : 0.0f; }
static void ft_font_line_metrics(FtFont *font, float *asc, float *desc, float *height) { FT_SizeRec *size; if (asc) *asc = 0.0f; if (desc) *desc = 0.0f; if (height) *height = 0.0f; if (!font || !font->face || !((FT_Face)font->face)->size) return; size = ((FT_Face)font->face)->size; if (asc) *asc = (float)size->metrics.ascender / FREETYPE_FIXED_POINT_SCALE; if (desc) *desc = (float)size->metrics.descender / FREETYPE_FIXED_POINT_SCALE; if (height) *height = (float)size->metrics.height / FREETYPE_FIXED_POINT_SCALE; }
static float compute_cell_width(FtFont *font) { static const uint32_t samples[] = { 'M', 'W', '@', '0' }; float width = 0.0f; size_t i; for (i = 0; i < RUDO_ARRAY_LEN(samples); ++i) { float a = ft_font_glyph_advance(font, samples[i]); if (a > width) width = a; } return width >= 1.0f ? width : 1.0f; }
static float compute_cell_height(FtFont *font) { float asc, desc, line_height, from_metrics; FT_GlyphSlotRec *slot; ft_font_line_metrics(font, &asc, &desc, &line_height); from_metrics = line_height; if (asc - desc > from_metrics) from_metrics = asc - desc; if (from_metrics > 0.0f) return from_metrics >= 1.0f ? from_metrics : 1.0f; if (font && font->face && ensure_ft() && !g_ft.Load_Char((FT_Face)font->face, (FT_ULong)'M', FT_LOAD_RENDER)) { slot = ((FT_Face)font->face)->glyph; if (slot && slot->bitmap.rows) return (float)slot->bitmap.rows >= 1.0f ? (float)slot->bitmap.rows : 1.0f; } return 1.0f; }
static unsigned ascii_cache_idx(unsigned char ch, int bold, int italic) { return (unsigned)(((bold != 0) * 2 + (italic != 0)) * ASCII_RANGE + (unsigned)(ch - 32u)); }
static uint32_t glyph_hash(uint32_t ch, uint8_t style) { uint32_t x = ch * 0x9e3779b1u; x ^= (uint32_t)style * 0x85ebca6bu; x ^= x >> 16; x *= 0x7feb352du; x ^= x >> 15; return x; }
static void glyph_cache_clear(rudo_font_atlas *atlas) { if (atlas->cache && atlas->cache_cap) memset(atlas->cache, 0, atlas->cache_cap * sizeof(atlas->cache[0])); atlas->cache_len = 0; }
static int glyph_cache_reserve(rudo_font_atlas *atlas, size_t need) { GlyphCacheEntry *old_entries = atlas->cache, *new_entries; size_t old_cap = atlas->cache_cap, new_cap = atlas->cache_cap ? atlas->cache_cap : 256u, i; if (atlas->cache_cap >= need && atlas->cache_cap) return 1; while (new_cap < need * 2u) new_cap *= 2u; new_entries = (GlyphCacheEntry *)calloc(new_cap, sizeof(GlyphCacheEntry)); if (!new_entries) return 0; atlas->cache = new_entries; atlas->cache_cap = new_cap; atlas->cache_len = 0; for (i = 0; i < old_cap; ++i) if (old_entries[i].used) { size_t idx = (size_t)glyph_hash(old_entries[i].ch, old_entries[i].style) & (atlas->cache_cap - 1u); while (atlas->cache[idx].used) idx = (idx + 1u) & (atlas->cache_cap - 1u); atlas->cache[idx] = old_entries[i]; ++atlas->cache_len; } free(old_entries); return 1; }
static int glyph_cache_lookup(rudo_font_atlas *atlas, uint32_t ch, uint8_t style, rudo_glyph_info *out) { size_t idx; if (!atlas->cache_cap || !atlas->cache) return 0; idx = (size_t)glyph_hash(ch, style) & (atlas->cache_cap - 1u); for (;;) { GlyphCacheEntry *entry = &atlas->cache[idx]; if (!entry->used) return 0; if (entry->style == style && entry->ch == ch) { *out = entry->glyph; return 1; } idx = (idx + 1u) & (atlas->cache_cap - 1u); } }
static void glyph_cache_insert(rudo_font_atlas *atlas, uint32_t ch, uint8_t style, rudo_glyph_info glyph) { size_t idx; if ((atlas->cache_len + 1u) * 10u >= atlas->cache_cap * 7u) { if (!glyph_cache_reserve(atlas, atlas->cache_len + 1u)) return; } else if (!atlas->cache_cap) { if (!glyph_cache_reserve(atlas, 1u)) return; } idx = (size_t)glyph_hash(ch, style) & (atlas->cache_cap - 1u); while (atlas->cache[idx].used) { if (atlas->cache[idx].style == style && atlas->cache[idx].ch == ch) { atlas->cache[idx].glyph = glyph; return; } idx = (idx + 1u) & (atlas->cache_cap - 1u); } atlas->cache[idx].used = 1u; atlas->cache[idx].style = style; atlas->cache[idx].ch = ch; atlas->cache[idx].glyph = glyph; ++atlas->cache_len; }
static void reset_atlas(rudo_font_atlas *atlas) { memset(atlas->ascii_populated, 0, sizeof(atlas->ascii_populated)); glyph_cache_clear(atlas); atlas->current_x = atlas->current_y = atlas->row_height = 0u; memset(atlas->atlas_data, 0, (size_t)ATLAS_WIDTH * (size_t)ATLAS_HEIGHT); }
static int ensure_fallback_font_capacity(rudo_font_atlas *atlas, size_t need) { return grow_array((void **)&atlas->fallback_fonts, sizeof(FtFont), &atlas->fallback_font_cap, need); }
static void ensure_fallback_paths(rudo_font_atlas *atlas) { char **paths; size_t len, i; if (atlas->fallback_paths_resolved) return; atlas->fallback_paths_resolved = 1; paths = fontconfig_sort_files(atlas->request, &len); for (i = 0; i < len; ++i) { if (!paths[i]) continue; if (atlas->regular.path && !strcmp(paths[i], atlas->regular.path)) continue; append_unique_string(&atlas->fallback_paths, &atlas->fallback_path_len, &atlas->fallback_path_cap, paths[i]); } free_string_array(paths, len); }
static void ensure_bold_font(rudo_font_atlas *atlas) { static const char *const styles[] = { "style=Bold" }; char *path; if (atlas->bold_state != FONT_SLOT_UNRESOLVED) return; path = resolve_style_font_path(atlas->request, styles, RUDO_ARRAY_LEN(styles)); if (!path || (atlas->regular.path && !strcmp(path, atlas->regular.path)) || !ft_font_load(&atlas->bold, path, atlas->font_size)) { atlas->bold_state = FONT_SLOT_FAILED; free(path); return; } atlas->bold_state = FONT_SLOT_READY; free(path); }
static void ensure_italic_font(rudo_font_atlas *atlas) { static const char *const styles[] = { "style=Italic", "style=Oblique" }; char *path; if (atlas->italic_state != FONT_SLOT_UNRESOLVED) return; path = resolve_style_font_path(atlas->request, styles, RUDO_ARRAY_LEN(styles)); if (!path || (atlas->regular.path && !strcmp(path, atlas->regular.path)) || !ft_font_load(&atlas->italic, path, atlas->font_size)) { atlas->italic_state = FONT_SLOT_FAILED; free(path); return; } atlas->italic_state = FONT_SLOT_READY; free(path); }
static void ensure_bold_italic_font(rudo_font_atlas *atlas) { static const char *const styles[] = { "style=Bold Italic", "style=Bold Oblique", "style=Italic Bold" }; char *path; if (atlas->bold_italic_state != FONT_SLOT_UNRESOLVED) return; path = resolve_style_font_path(atlas->request, styles, RUDO_ARRAY_LEN(styles)); if (!path || (atlas->regular.path && !strcmp(path, atlas->regular.path)) || !ft_font_load(&atlas->bold_italic, path, atlas->font_size)) { atlas->bold_italic_state = FONT_SLOT_FAILED; free(path); return; } atlas->bold_italic_state = FONT_SLOT_READY; free(path); }
static FtFont *pick_styled_font(rudo_font_atlas *atlas, int bold, int italic) { if (bold && italic) { ensure_bold_italic_font(atlas); if (atlas->bold_italic_state == FONT_SLOT_READY) return &atlas->bold_italic; ensure_bold_font(atlas); if (atlas->bold_state == FONT_SLOT_READY) return &atlas->bold; ensure_italic_font(atlas); if (atlas->italic_state == FONT_SLOT_READY) return &atlas->italic; return &atlas->regular; } if (bold) { ensure_bold_font(atlas); return atlas->bold_state == FONT_SLOT_READY ? &atlas->bold : &atlas->regular; } if (italic) { ensure_italic_font(atlas); return atlas->italic_state == FONT_SLOT_READY ? &atlas->italic : &atlas->regular; } return &atlas->regular; }
static FtFont *pick_font_with_fallback(rudo_font_atlas *atlas, uint32_t ch, int bold, int italic) { FtFont *styled = pick_styled_font(atlas, bold, italic); size_t i; if (ch < 128u) return styled; if (ft_font_has_glyph(styled, ch)) return styled; if (ft_font_has_glyph(&atlas->regular, ch)) return &atlas->regular; for (i = 0; i < atlas->fallback_font_len; ++i) if (ft_font_has_glyph(&atlas->fallback_fonts[i], ch)) return &atlas->fallback_fonts[i]; ensure_fallback_paths(atlas); while (atlas->next_fallback_path < atlas->fallback_path_len) { FtFont font; const char *path = atlas->fallback_paths[atlas->next_fallback_path++]; ft_font_init(&font); if (!ft_font_load(&font, path, atlas->font_size)) continue; if (!ensure_fallback_font_capacity(atlas, atlas->fallback_font_len + 1u)) { ft_font_drop(&font); break; } atlas->fallback_fonts[atlas->fallback_font_len++] = font; if (ft_font_has_glyph(&atlas->fallback_fonts[atlas->fallback_font_len - 1u], ch)) return &atlas->fallback_fonts[atlas->fallback_font_len - 1u]; } return styled; }
static void copy_bitmap_rows(uint8_t *atlas_data, unsigned atlas_x, unsigned atlas_y, const FT_Bitmap *bitmap) { unsigned row; if (!bitmap || !bitmap->buffer || !bitmap->width || !bitmap->rows) return; for (row = 0; row < bitmap->rows; ++row) { const unsigned char *src = bitmap->pitch < 0 ? bitmap->buffer + (ptrdiff_t)row * (ptrdiff_t)bitmap->pitch : bitmap->buffer + (size_t)row * (size_t)bitmap->pitch; uint8_t *dst = atlas_data + ((size_t)(atlas_y + row) * (size_t)ATLAS_WIDTH + (size_t)atlas_x); memcpy(dst, src, bitmap->width); } }
static rudo_glyph_info rasterize_glyph(rudo_font_atlas *atlas, uint32_t ch, int bold, int italic) { FtFont *font; FT_GlyphSlotRec *slot; FT_Bitmap *bitmap; unsigned gw, gh, ax = 0, ay = 0; rudo_glyph_info info = empty_glyph_info(); font = pick_font_with_fallback(atlas, ch, bold, italic); if (!font || !font->face || !ensure_ft()) return info; if (g_ft.Load_Char((FT_Face)font->face, (FT_ULong)ch, FT_LOAD_RENDER)) return info; slot = ((FT_Face)font->face)->glyph; if (!slot) return info; bitmap = &slot->bitmap; gw = bitmap->width; gh = bitmap->rows; if (gw && gh) { if (atlas->current_x + gw > ATLAS_WIDTH) { atlas->current_y += atlas->row_height; atlas->current_x = atlas->row_height = 0u; } if (atlas->current_y + gh > ATLAS_HEIGHT) reset_atlas(atlas); if (atlas->current_x + gw > ATLAS_WIDTH) { atlas->current_y += atlas->row_height; atlas->current_x = atlas->row_height = 0u; } if (atlas->current_y + gh > ATLAS_HEIGHT) return info; ax = atlas->current_x; ay = atlas->current_y; copy_bitmap_rows(atlas->atlas_data, ax, ay, bitmap); atlas->current_x += gw + 1u; if (gh + 1u > atlas->row_height) atlas->row_height = gh + 1u; }
    info.u0 = (float)ax / (float)ATLAS_WIDTH; info.v0 = (float)ay / (float)ATLAS_HEIGHT; info.u1 = (float)(ax + gw) / (float)ATLAS_WIDTH; info.v1 = (float)(ay + gh) / (float)ATLAS_HEIGHT; info.width = (float)gw; info.height = (float)gh; info.offset_x = (float)slot->bitmap_left; info.offset_y = (float)(slot->bitmap_top - (int)gh); return info; }

rudo_font_atlas *rudo_font_atlas_new(float font_size, const char *preferred_family) { rudo_font_atlas *atlas; char *request, *regular_path; if (font_size < 1.0f) font_size = 1.0f; atlas = (rudo_font_atlas *)calloc(1u, sizeof(*atlas)); if (!atlas) return NULL; ft_font_init(&atlas->regular); ft_font_init(&atlas->bold); ft_font_init(&atlas->italic); ft_font_init(&atlas->bold_italic); request = trimmed_copy(preferred_family); if (!request) { free(atlas); return NULL; } regular_path = resolve_regular_font_path(request); if (!regular_path || !ft_font_load(&atlas->regular, regular_path, font_size)) { free(regular_path); free(request); free(atlas); fprintf(stderr, "[ERROR] No usable font found for '%s'\n", preferred_family ? preferred_family : RUDO_DEFAULT_FONT_FAMILY); return NULL; } atlas->atlas_data = (uint8_t *)calloc((size_t)ATLAS_WIDTH * (size_t)ATLAS_HEIGHT, 1u); if (!atlas->atlas_data) { free(regular_path); ft_font_drop(&atlas->regular); free(request); free(atlas); return NULL; } atlas->request = request; atlas->font_size = font_size; atlas->cell_width = compute_cell_width(&atlas->regular); atlas->cell_height = compute_cell_height(&atlas->regular); { float asc, desc, height; ft_font_line_metrics(&atlas->regular, &asc, &desc, &height); RUDO_UNUSED(desc); RUDO_UNUSED(height); atlas->baseline = asc > 0.0f ? asc : atlas->cell_height * FALLBACK_BASELINE_RATIO; } free(regular_path); return atlas; }
void rudo_font_atlas_free(rudo_font_atlas *atlas) { size_t i; if (!atlas) return; ft_font_drop(&atlas->regular); ft_font_drop(&atlas->bold); ft_font_drop(&atlas->italic); ft_font_drop(&atlas->bold_italic); for (i = 0; i < atlas->fallback_font_len; ++i) ft_font_drop(&atlas->fallback_fonts[i]); free(atlas->fallback_fonts); free_string_array(atlas->fallback_paths, atlas->fallback_path_len); free(atlas->atlas_data); free(atlas->cache); free(atlas->request); free(atlas); }
float rudo_font_atlas_cell_width(const rudo_font_atlas *atlas) { return atlas ? atlas->cell_width : 0.0f; }
float rudo_font_atlas_cell_height(const rudo_font_atlas *atlas) { return atlas ? atlas->cell_height : 0.0f; }
float rudo_font_atlas_baseline(const rudo_font_atlas *atlas) { return atlas ? atlas->baseline : 0.0f; }
rudo_glyph_info rudo_font_atlas_get_glyph(rudo_font_atlas *atlas, uint32_t ch, bool bold, bool italic) { rudo_glyph_info glyph; uint8_t style; if (!atlas) return empty_glyph_info(); if (ch >= 32u && ch <= 126u) { unsigned idx = ascii_cache_idx((unsigned char)ch, bold, italic); if (!atlas->ascii_populated[idx]) { atlas->ascii_cache[idx] = rasterize_glyph(atlas, ch, bold, italic); atlas->ascii_populated[idx] = 1u; } return atlas->ascii_cache[idx]; } style = (uint8_t)(((bold != 0) << 1) | (italic != 0)); if (glyph_cache_lookup(atlas, ch, style, &glyph)) return glyph; glyph = rasterize_glyph(atlas, ch, bold, italic); glyph_cache_insert(atlas, ch, style, glyph); return glyph; }
const uint8_t *rudo_font_atlas_data(const rudo_font_atlas *atlas, size_t *len_out) { if (len_out) *len_out = atlas ? (size_t)ATLAS_WIDTH * (size_t)ATLAS_HEIGHT : 0u; return atlas ? atlas->atlas_data : NULL; }
uint32_t rudo_font_atlas_width(const rudo_font_atlas *atlas) { RUDO_UNUSED(atlas); return ATLAS_WIDTH; }
uint32_t rudo_font_atlas_height(const rudo_font_atlas *atlas) { RUDO_UNUSED(atlas); return ATLAS_HEIGHT; }
