#include "rudo/render.h"
#include <math.h>
#include <float.h>
#include <string.h>

#define EDGE_STRIP_DISTANCE_SQ 0.8f
#define EDGE_STRIP_RADIUS 0.8944272f
#define FLOAT_CHANGE_EPSILON 0.001f
#define AXIS_ALIGNED_QUAD_EPSILON 0.01f
#define BT709_LUMA_RED 0.2126f
#define BT709_LUMA_GREEN 0.7152f
#define BT709_LUMA_BLUE 0.0722f
#define LUMA_CONTRAST_THRESHOLD 0.5f
#define DEFAULT_FONT_DPI 96.0f
#define POINTS_PER_INCH 72.0f
#define DEGENERATE_EDGE_EPSILON_SQ 0.0001f

typedef struct { uint32_t x, y, width, height; } rect;
struct rudo_software_renderer { rudo_font_atlas *font; rudo_theme_colors theme; char *font_family; float font_size, base_font_size, scale, cell_width, cell_height, baseline, offset_x, offset_y; uint32_t padding; uint32_t *col_boundaries, *row_boundaries; size_t col_cap, row_cap, cols, rows; uint8_t background_alpha; };
static uint16_t div255(uint16_t v) { uint16_t t = (uint16_t)(v + 128u); return (uint16_t)((t + (t >> 8)) >> 8); }
static rudo_rgb rgb_from_u32(uint32_t c) { rudo_rgb v = { (uint8_t)((c >> 16) & 255u), (uint8_t)((c >> 8) & 255u), (uint8_t)(c & 255u) }; return v; }
static uint32_t pixel_boundary(float origin, float step, size_t index) { float v = roundf(origin + step * (float)index); if (v < 0.0f) v = 0.0f; return (uint32_t)v; }
static void anchored_grid_layout(uint32_t width, uint32_t height, float cell_width, float cell_height, uint32_t padding, float scale, size_t *cols, size_t *rows, float *ox, float *oy) { float cw = cell_width > 1.0f ? cell_width : 1.0f, ch = cell_height > 1.0f ? cell_height : 1.0f, phys_pad = (float)padding * scale, usable_w = (float)width - phys_pad * 2.0f, usable_h = (float)height - phys_pad * 2.0f; if (usable_w < 0.0f) usable_w = 0.0f; if (usable_h < 0.0f) usable_h = 0.0f; *cols = (size_t)RUDO_MAX(floorf(usable_w / cw), 1.0f); *rows = (size_t)RUDO_MAX(floorf(usable_h / ch), 1.0f); *ox = phys_pad < (float)width ? phys_pad : (float)width; *oy = phys_pad < (float)height ? phys_pad : (float)height; }
static float font_size_in_pixels(float font_size, float scale) { if (font_size < 1.0f) font_size = 1.0f; if (scale < 1.0f) scale = 1.0f; return RUDO_MAX(font_size * scale * DEFAULT_FONT_DPI / POINTS_PER_INCH, 1.0f); }
static void ensure_bounds(struct rudo_software_renderer *r, size_t cols, size_t rows) { size_t i; if (cols + 1u > r->col_cap) { r->col_cap = cols + 1u; r->col_boundaries = (uint32_t *)realloc(r->col_boundaries, r->col_cap * sizeof(uint32_t)); } if (rows + 1u > r->row_cap) { r->row_cap = rows + 1u; r->row_boundaries = (uint32_t *)realloc(r->row_boundaries, r->row_cap * sizeof(uint32_t)); } for (i = 0; i <= cols; ++i) r->col_boundaries[i] = pixel_boundary(r->offset_x, r->cell_width, i); for (i = 0; i <= rows; ++i) r->row_boundaries[i] = pixel_boundary(r->offset_y, r->cell_height, i); r->cols = cols; r->rows = rows; }
static void rebuild_font(struct rudo_software_renderer *r) { float physical_size = font_size_in_pixels(r->font_size, r->scale); rudo_font_atlas *font = rudo_font_atlas_new(physical_size, r->font_family); if (!font) return; rudo_font_atlas_free(r->font); r->font = font; r->cell_width = RUDO_MAX(rudo_font_atlas_cell_width(font), 1.0f); r->cell_height = RUDO_MAX(rudo_font_atlas_cell_height(font), 1.0f); r->baseline = rudo_font_atlas_baseline(font); }
static void put_bgra(rudo_framebuffer *fb, uint32_t x, uint32_t y, rudo_rgb c, uint8_t a) { size_t o; if (!fb || x >= fb->width || y >= fb->height) return; o = (size_t)y * fb->stride + (size_t)x * 4u; fb->pixels[o + 0] = c.b; fb->pixels[o + 1] = c.g; fb->pixels[o + 2] = c.r; fb->pixels[o + 3] = a; }
static void blend_bgra(rudo_framebuffer *fb, uint32_t x, uint32_t y, rudo_rgb c, uint8_t a) { size_t o; uint8_t db, dg, dr, da; uint16_t ia; if (!fb || !a || x >= fb->width || y >= fb->height) return; if (a == 255) { put_bgra(fb, x, y, c, 255); return; } o = (size_t)y * fb->stride + (size_t)x * 4u; db = fb->pixels[o + 0]; dg = fb->pixels[o + 1]; dr = fb->pixels[o + 2]; da = fb->pixels[o + 3]; ia = (uint16_t)(255u - a); fb->pixels[o + 0] = (uint8_t)(div255((uint16_t)c.b * a + (uint16_t)db * ia)); fb->pixels[o + 1] = (uint8_t)(div255((uint16_t)c.g * a + (uint16_t)dg * ia)); fb->pixels[o + 2] = (uint8_t)(div255((uint16_t)c.r * a + (uint16_t)dr * ia)); fb->pixels[o + 3] = (uint8_t)RUDO_MIN(255u, a + div255((uint16_t)da * ia)); }
static void fill_rect_raw(rudo_framebuffer *fb, rect rc, rudo_rgb c) { uint32_t y, x, max_x = RUDO_MIN(rc.x + rc.width, fb->width), max_y = RUDO_MIN(rc.y + rc.height, fb->height); for (y = rc.y; y < max_y; ++y) for (x = rc.x; x < max_x; ++x) put_bgra(fb, x, y, c, 255); }
static void fill_rect_raw_alpha(rudo_framebuffer *fb, rect rc, rudo_rgb c, uint8_t a) { uint32_t y, x, max_x = RUDO_MIN(rc.x + rc.width, fb->width), max_y = RUDO_MIN(rc.y + rc.height, fb->height); for (y = rc.y; y < max_y; ++y) for (x = rc.x; x < max_x; ++x) blend_bgra(fb, x, y, c, a); }
static void fill_rect_raw_alpha_overwrite(rudo_framebuffer *fb, rect rc, rudo_rgb c, uint8_t a) { uint32_t y, x, max_x = RUDO_MIN(rc.x + rc.width, fb->width), max_y = RUDO_MIN(rc.y + rc.height, fb->height); uint8_t pb = a == 255 ? c.b : (uint8_t)div255((uint16_t)c.b * a), pg = a == 255 ? c.g : (uint8_t)div255((uint16_t)c.g * a), pr = a == 255 ? c.r : (uint8_t)div255((uint16_t)c.r * a); size_t o; for (y = rc.y; y < max_y; ++y) for (x = rc.x; x < max_x; ++x) { o = (size_t)y * fb->stride + (size_t)x * 4u; fb->pixels[o + 0] = pb; fb->pixels[o + 1] = pg; fb->pixels[o + 2] = pr; fb->pixels[o + 3] = a; } }
static bool point_in_triangle(float px, float py, float ax, float ay, float bx, float by, float cx, float cy) { float s1 = (px - cx) * (ay - cy) - (ax - cx) * (py - cy), s2 = (px - ax) * (by - ay) - (bx - ax) * (py - ay), s3 = (px - bx) * (cy - by) - (cx - bx) * (py - by); bool neg = s1 < 0.0f || s2 < 0.0f || s3 < 0.0f, pos = s1 > 0.0f || s2 > 0.0f || s3 > 0.0f; return !(neg && pos); }
static void quad_aabb(const float q[8], uint32_t *min_x, uint32_t *min_y, uint32_t *max_x, uint32_t *max_y) { float lo_x = q[0], lo_y = q[1], hi_x = q[0], hi_y = q[1]; int i; for (i = 1; i < 4; ++i) { float x = q[i * 2], y = q[i * 2 + 1]; if (x < lo_x) lo_x = x; else if (x > hi_x) hi_x = x; if (y < lo_y) lo_y = y; else if (y > hi_y) hi_y = y; } *min_x = (uint32_t)RUDO_MAX(floorf(lo_x), 0.0f); *min_y = (uint32_t)RUDO_MAX(floorf(lo_y), 0.0f); *max_x = (uint32_t)RUDO_MAX(ceilf(hi_x), 0.0f); *max_y = (uint32_t)RUDO_MAX(ceilf(hi_y), 0.0f); }
static bool axis_aligned_quad_fill_bounds(const float q[8], uint32_t fb_width, uint32_t fb_height, uint32_t *x, uint32_t *y, uint32_t *w, uint32_t *h) { float min_x = q[0], min_y = q[1], max_x = q[0], max_y = q[1]; float expected[8]; uint32_t x0, y0, x1, y1; int i; for (i = 1; i < 4; ++i) { if (q[i * 2] < min_x) min_x = q[i * 2]; if (q[i * 2 + 1] < min_y) min_y = q[i * 2 + 1]; if (q[i * 2] > max_x) max_x = q[i * 2]; if (q[i * 2 + 1] > max_y) max_y = q[i * 2 + 1]; } expected[0] = min_x; expected[1] = min_y; expected[2] = max_x; expected[3] = min_y; expected[4] = max_x; expected[5] = max_y; expected[6] = min_x; expected[7] = max_y; for (i = 0; i < 8; ++i) if (fabsf(q[i] - expected[i]) > AXIS_ALIGNED_QUAD_EPSILON) return false; x0 = (uint32_t)RUDO_CLAMP(ceilf(min_x - 0.5f), 0.0f, (float)fb_width); x1 = (uint32_t)RUDO_CLAMP(floorf(max_x - 0.5f) + 1.0f, 0.0f, (float)fb_width); y0 = (uint32_t)RUDO_CLAMP(ceilf(min_y - 0.5f), 0.0f, (float)fb_height); y1 = (uint32_t)RUDO_CLAMP(floorf(max_y - 0.5f) + 1.0f, 0.0f, (float)fb_height); if (x1 <= x0 || y1 <= y0) return false; *x = x0; *y = y0; *w = x1 - x0; *h = y1 - y0; return true; }
static void fill_quad(rudo_framebuffer *fb, const float q[8], rudo_rgb c) { uint32_t min_x, min_y, max_x, max_y, x, y, w, h; if (axis_aligned_quad_fill_bounds(q, fb->width, fb->height, &x, &y, &w, &h)) { fill_rect_raw(fb, (rect){ x, y, w, h }, c); return; } quad_aabb(q, &min_x, &min_y, &max_x, &max_y); for (y = min_y; y < RUDO_MIN(max_y, fb->height); ++y) for (x = min_x; x < RUDO_MIN(max_x, fb->width); ++x) { float px = (float)x + 0.5f, py = (float)y + 0.5f; if (point_in_triangle(px, py, q[0], q[1], q[2], q[3], q[4], q[5]) || point_in_triangle(px, py, q[0], q[1], q[4], q[5], q[6], q[7])) put_bgra(fb, x, y, c, 255); } }
static void fill_quad_alpha(rudo_framebuffer *fb, const float q[8], rudo_rgb c, uint8_t a) { uint32_t min_x, min_y, max_x, max_y, x, y; if (!a) return; quad_aabb(q, &min_x, &min_y, &max_x, &max_y); for (y = min_y; y < RUDO_MIN(max_y, fb->height); ++y) for (x = min_x; x < RUDO_MIN(max_x, fb->width); ++x) { float px = (float)x + 0.5f, py = (float)y + 0.5f; if (point_in_triangle(px, py, q[0], q[1], q[2], q[3], q[4], q[5]) || point_in_triangle(px, py, q[0], q[1], q[4], q[5], q[6], q[7])) blend_bgra(fb, x, y, c, a); } }
static void fill_edge_strip(rudo_framebuffer *fb, float x0, float y0, float x1, float y1, rudo_rgb c, uint8_t a) { float dx = x1 - x0, dy = y1 - y0, len_sq = dx * dx + dy * dy; int min_x, min_y, max_x, max_y; uint32_t x, y; float inv_length_sq; if (len_sq <= DEGENERATE_EDGE_EPSILON_SQ || !a) return; if (fabsf(dx) < AXIS_ALIGNED_QUAD_EPSILON) { float cx = (x0 + x1) * 0.5f; fill_rect_raw_alpha(fb, (rect){ (uint32_t)RUDO_MAX(floorf(cx - EDGE_STRIP_RADIUS), 0.0f), (uint32_t)RUDO_MAX(floorf(RUDO_MIN(y0, y1)), 0.0f), (uint32_t)RUDO_MIN(ceilf(cx + EDGE_STRIP_RADIUS), (float)fb->width) - (uint32_t)RUDO_MAX(floorf(cx - EDGE_STRIP_RADIUS), 0.0f), (uint32_t)RUDO_MIN(ceilf(RUDO_MAX(y0, y1)), (float)fb->height) - (uint32_t)RUDO_MAX(floorf(RUDO_MIN(y0, y1)), 0.0f) }, c, a); return; }
    if (fabsf(dy) < AXIS_ALIGNED_QUAD_EPSILON) { float cy = (y0 + y1) * 0.5f; fill_rect_raw_alpha(fb, (rect){ (uint32_t)RUDO_MAX(floorf(RUDO_MIN(x0, x1)), 0.0f), (uint32_t)RUDO_MAX(floorf(cy - EDGE_STRIP_RADIUS), 0.0f), (uint32_t)RUDO_MIN(ceilf(RUDO_MAX(x0, x1)), (float)fb->width) - (uint32_t)RUDO_MAX(floorf(RUDO_MIN(x0, x1)), 0.0f), (uint32_t)RUDO_MIN(ceilf(cy + EDGE_STRIP_RADIUS), (float)fb->height) - (uint32_t)RUDO_MAX(floorf(cy - EDGE_STRIP_RADIUS), 0.0f) }, c, a); return; }
    min_x = (int)floorf(RUDO_MIN(x0, x1)) - 1; max_x = (int)ceilf(RUDO_MAX(x0, x1)) + 1; min_y = (int)floorf(RUDO_MIN(y0, y1)) - 1; max_y = (int)ceilf(RUDO_MAX(y0, y1)) + 1; inv_length_sq = 1.0f / len_sq; for (y = (uint32_t)RUDO_MAX(min_y, 0); y < RUDO_MIN((uint32_t)RUDO_MAX(max_y, 0), fb->height); ++y) { float py = (float)y + 0.5f, from_start_y = py - y0, y_dot = from_start_y * dy; for (x = (uint32_t)RUDO_MAX(min_x, 0); x < RUDO_MIN((uint32_t)RUDO_MAX(max_x, 0), fb->width); ++x) { float px = (float)x + 0.5f, from_start_x = px - x0, along = RUDO_CLAMP((from_start_x * dx + y_dot) * inv_length_sq, 0.0f, 1.0f), cx = x0 + along * dx, cy = y0 + along * dy, ddx = px - cx, ddy = py - cy; if (ddx * ddx + ddy * ddy <= EDGE_STRIP_DISTANCE_SQ) blend_bgra(fb, x, y, c, a); } } }
static void stroke_quad_edges_alpha(rudo_framebuffer *fb, const float q[8], rudo_rgb c, uint8_t a) { fill_edge_strip(fb, q[0], q[1], q[2], q[3], c, a); fill_edge_strip(fb, q[2], q[3], q[4], q[5], c, a); fill_edge_strip(fb, q[4], q[5], q[6], q[7], c, a); fill_edge_strip(fb, q[6], q[7], q[0], q[1], c, a); }
static void draw_unfocused_outline(rudo_framebuffer *fb, const float q[8], rudo_rgb c, uint8_t a, float stroke_px) { float half = stroke_px * 0.5f, dist_sq = half * half; int e; if (!a) return; for (e = 0; e < 4; ++e) { float x0 = q[(e * 2) % 8], y0 = q[(e * 2 + 1) % 8], x1 = q[((e + 1) * 2) % 8], y1 = q[((e + 1) * 2 + 1) % 8], dx = x1 - x0, dy = y1 - y0, len_sq = dx * dx + dy * dy; uint32_t x, y, min_x, min_y, max_x, max_y; float inv; if (len_sq <= DEGENERATE_EDGE_EPSILON_SQ) continue; min_x = (uint32_t)RUDO_MAX(floorf(RUDO_MIN(x0, x1) - half), 0.0f); max_x = (uint32_t)RUDO_MIN(ceilf(RUDO_MAX(x0, x1) + half), (float)fb->width); min_y = (uint32_t)RUDO_MAX(floorf(RUDO_MIN(y0, y1) - half), 0.0f); max_y = (uint32_t)RUDO_MIN(ceilf(RUDO_MAX(y0, y1) + half), (float)fb->height); inv = 1.0f / len_sq; for (y = min_y; y < max_y; ++y) { float py = (float)y + 0.5f, from_start_y = py - y0, y_dot = from_start_y * dy; for (x = min_x; x < max_x; ++x) { float px = (float)x + 0.5f, from_start_x = px - x0, along = RUDO_CLAMP((from_start_x * dx + y_dot) * inv, 0.0f, 1.0f), cx = x0 + along * dx, cy = y0 + along * dy, ddx = px - cx, ddy = py - cy; if (ddx * ddx + ddy * ddy <= dist_sq) blend_bgra(fb, x, y, c, a); } } } }
static rudo_rgb contrasting_cursor_text_color(rudo_rgb c) { float luma = (c.r / 255.0f) * BT709_LUMA_RED + (c.g / 255.0f) * BT709_LUMA_GREEN + (c.b / 255.0f) * BT709_LUMA_BLUE; return luma > LUMA_CONTRAST_THRESHOLD ? (rudo_rgb){ 0,0,0 } : (rudo_rgb){ 255,255,255 }; }
static void fill_subrect(rudo_framebuffer *fb, rect rc, float x0, float y0, float x1, float y1, rudo_rgb c) { uint32_t left = rc.x + (uint32_t)RUDO_CLAMP(floorf((float)rc.width * x0), 0.0f, (float)rc.width); uint32_t top = rc.y + (uint32_t)RUDO_CLAMP(floorf((float)rc.height * y0), 0.0f, (float)rc.height); uint32_t right = rc.x + (uint32_t)RUDO_CLAMP(ceilf((float)rc.width * x1), 0.0f, (float)rc.width); uint32_t bottom = rc.y + (uint32_t)RUDO_CLAMP(ceilf((float)rc.height * y1), 0.0f, (float)rc.height); if (right > left && bottom > top) fill_rect_raw(fb, (rect){ left, top, right - left, bottom - top }, c); }
static void fill_box_horizontal(rudo_framebuffer *fb, rect rc, float y, float thickness, float x0, float x1, rudo_rgb c) { fill_subrect(fb, rc, x0, y - thickness * 0.5f, x1, y + thickness * 0.5f, c); }
static void fill_box_vertical(rudo_framebuffer *fb, rect rc, float x, float thickness, float y0, float y1, rudo_rgb c) { fill_subrect(fb, rc, x - thickness * 0.5f, y0, x + thickness * 0.5f, y1, c); }
static bool draw_native_box_char(rudo_framebuffer *fb, rect rc, uint32_t ch, rudo_rgb c) { const float l = 0.16f, h = 0.28f; switch (ch) {
    case 0x2500: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x2501: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 1.0f, c); break;
    case 0x2550: fill_box_horizontal(fb, rc, 0.34f, l, 0.0f, 1.0f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.0f, 1.0f, c); break;
    case 0x2502: fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x2503: fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 1.0f, c); break;
    case 0x2551: fill_box_vertical(fb, rc, 0.34f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.0f, 1.0f, c); break;
    case 0x250c: fill_box_horizontal(fb, rc, 0.5f, l, 0.5f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.5f, 1.0f, c); break;
    case 0x2510: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 0.5f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.5f, 1.0f, c); break;
    case 0x2514: fill_box_horizontal(fb, rc, 0.5f, l, 0.5f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 0.5f, c); break;
    case 0x2518: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 0.5f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 0.5f, c); break;
    case 0x250f: fill_box_horizontal(fb, rc, 0.5f, h, 0.5f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.5f, 1.0f, c); break;
    case 0x2513: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 0.5f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.5f, 1.0f, c); break;
    case 0x2517: fill_box_horizontal(fb, rc, 0.5f, h, 0.5f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 0.5f, c); break;
    case 0x251b: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 0.5f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 0.5f, c); break;
    case 0x2554: fill_box_horizontal(fb, rc, 0.34f, l, 0.34f, 1.0f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.34f, 1.0f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.34f, 1.0f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.34f, 1.0f, c); break;
    case 0x2557: fill_box_horizontal(fb, rc, 0.34f, l, 0.0f, 0.66f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.0f, 0.66f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.34f, 1.0f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.34f, 1.0f, c); break;
    case 0x255a: fill_box_horizontal(fb, rc, 0.34f, l, 0.34f, 1.0f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.34f, 1.0f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.0f, 0.66f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.0f, 0.66f, c); break;
    case 0x255d: fill_box_horizontal(fb, rc, 0.34f, l, 0.0f, 0.66f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.0f, 0.66f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.0f, 0.66f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.0f, 0.66f, c); break;
    case 0x251c: fill_box_horizontal(fb, rc, 0.5f, l, 0.5f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x2524: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 0.5f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x252c: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.5f, 1.0f, c); break;
    case 0x2534: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 0.5f, c); break;
    case 0x253c: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x2523: fill_box_horizontal(fb, rc, 0.5f, h, 0.5f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 1.0f, c); break;
    case 0x252b: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 0.5f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 1.0f, c); break;
    case 0x2533: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.5f, 1.0f, c); break;
    case 0x253b: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 0.5f, c); break;
    case 0x254b: fill_box_horizontal(fb, rc, 0.5f, h, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, h, 0.0f, 1.0f, c); break;
    case 0x2560: fill_box_horizontal(fb, rc, 0.34f, l, 0.34f, 1.0f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.34f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x2563: fill_box_horizontal(fb, rc, 0.34f, l, 0.0f, 0.66f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.0f, 0.66f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); break;
    case 0x2566: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.34f, 1.0f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.34f, 1.0f, c); break;
    case 0x2569: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.0f, 0.66f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.0f, 0.66f, c); break;
    case 0x256c: fill_box_horizontal(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_vertical(fb, rc, 0.5f, l, 0.0f, 1.0f, c); fill_box_horizontal(fb, rc, 0.34f, l, 0.34f, 0.66f, c); fill_box_horizontal(fb, rc, 0.66f, l, 0.34f, 0.66f, c); fill_box_vertical(fb, rc, 0.34f, l, 0.34f, 0.66f, c); fill_box_vertical(fb, rc, 0.66f, l, 0.34f, 0.66f, c); break;
    default: return false;
    } return true; }
static bool draw_native_block_char(rudo_framebuffer *fb, rect rc, uint32_t ch, rudo_rgb c) { switch (ch) { case 0x2588: fill_rect_raw(fb, rc, c); break; case 0x2580: fill_rect_raw(fb, (rect){ rc.x, rc.y, rc.width, rc.height / 2u }, c); break; case 0x2584: fill_rect_raw(fb, (rect){ rc.x, rc.y + rc.height / 2u, rc.width, rc.height - rc.height / 2u }, c); break; case 0x258C: fill_rect_raw(fb, (rect){ rc.x, rc.y, rc.width / 2u, rc.height }, c); break; case 0x2590: fill_rect_raw(fb, (rect){ rc.x + rc.width / 2u, rc.y, rc.width - rc.width / 2u, rc.height }, c); break; default: return false; } return true; }
static void blit_glyph_fast(rudo_framebuffer *fb, const uint8_t *atlas, uint32_t src_x, uint32_t src_y, size_t src_stride, uint32_t dst_x, uint32_t dst_y, uint32_t draw_w, uint32_t draw_h, rudo_rgb c) { uint32_t row, col; for (row = 0; row < draw_h; ++row) { size_t src_row = (size_t)(src_y + row) * src_stride + src_x; uint32_t dy = dst_y + row; for (col = 0; col < draw_w; ++col) { uint8_t a = atlas[src_row + col]; if (a) blend_bgra(fb, dst_x + col, dy, c, a); } } }
static void draw_glyph(rudo_software_renderer *r, rudo_framebuffer *fb, uint32_t cell_x, uint32_t cell_y, uint32_t cell_w, uint32_t cell_h, uint32_t ch, rudo_rgb c, bool bold, bool italic, const float *clip_quad) { rudo_glyph_info g; uint32_t atlas_w, atlas_h, src_left, src_top, glyph_width, glyph_height, src_width, src_height, skip_left, skip_top, skip_right, skip_bottom, draw_w, draw_h, src_x, src_y, dst_x, dst_y, row, col; size_t len, src_stride; const uint8_t *atlas; int dst_left, dst_top; if (!clip_quad && (draw_native_block_char(fb, (rect){ cell_x, cell_y, cell_w, cell_h }, ch, c) || draw_native_box_char(fb, (rect){ cell_x, cell_y, cell_w, cell_h }, ch, c))) return; g = rudo_font_atlas_get_glyph(r->font, ch, bold, italic); if (g.width <= 0.0f || g.height <= 0.0f) return; atlas_w = rudo_font_atlas_width(r->font); atlas_h = rudo_font_atlas_height(r->font); atlas = rudo_font_atlas_data(r->font, &len); RUDO_UNUSED(len); src_left = (uint32_t)lroundf(g.u0 * (float)atlas_w); src_top = (uint32_t)lroundf(g.v0 * (float)atlas_h); glyph_width = (uint32_t)g.width; glyph_height = (uint32_t)g.height; dst_left = (int)lroundf((float)cell_x + g.offset_x); dst_top = (int)lroundf((float)cell_y + r->baseline - g.height - g.offset_y); src_width = RUDO_MIN(glyph_width, atlas_w - src_left); src_height = RUDO_MIN(glyph_height, atlas_h - src_top); if (!src_width || !src_height) return; skip_left = (uint32_t)RUDO_MAX(-dst_left, 0); skip_top = (uint32_t)RUDO_MAX(-dst_top, 0); skip_right = (uint32_t)RUDO_MAX(dst_left + (int)src_width - (int)fb->width, 0); skip_bottom = (uint32_t)RUDO_MAX(dst_top + (int)src_height - (int)fb->height, 0); draw_w = src_width - skip_left - skip_right; draw_h = src_height - skip_top - skip_bottom; if (!draw_w || !draw_h) return; src_x = src_left + skip_left; src_y = src_top + skip_top; dst_x = (uint32_t)(dst_left + (int)skip_left); dst_y = (uint32_t)(dst_top + (int)skip_top); src_stride = atlas_w; if (!clip_quad) { blit_glyph_fast(fb, atlas, src_x, src_y, src_stride, dst_x, dst_y, draw_w, draw_h, c); return; } for (row = 0; row < draw_h; ++row) { size_t src_row = (size_t)(src_y + row) * src_stride + src_x; uint32_t dy = dst_y + row; for (col = 0; col < draw_w; ++col) { uint8_t a = atlas[src_row + col]; uint32_t dx = dst_x + col; float px, py; if (!a) continue; px = (float)dx + 0.5f; py = (float)dy + 0.5f; if (!point_in_triangle(px, py, clip_quad[0], clip_quad[1], clip_quad[2], clip_quad[3], clip_quad[4], clip_quad[5]) && !point_in_triangle(px, py, clip_quad[0], clip_quad[1], clip_quad[4], clip_quad[5], clip_quad[6], clip_quad[7])) continue; blend_bgra(fb, dx, dy, c, a); } } }
static void draw_vfx_particles(const rudo_software_renderer *r, rudo_framebuffer *fb, const rudo_cursor_renderer *cursor) { size_t n = rudo_cursor_renderer_particle_count(cursor), i; rudo_cursor_particle *p; rudo_rgb cc = rgb_from_u32(((uint32_t)r->theme.cursor[0] << 16) | ((uint32_t)r->theme.cursor[1] << 8) | (uint32_t)r->theme.cursor[2]); if (!n) return; p = (rudo_cursor_particle *)malloc(n * sizeof(*p)); if (!p) return; n = rudo_cursor_renderer_particles(cursor, p, n); for (i = 0; i < n; ++i) { float px = r->offset_x + p[i].x * r->cell_width, py = r->offset_y + p[i].y * r->cell_height, rx = p[i].radius * r->cell_width * 0.5f, ry = p[i].radius * r->cell_height * 0.5f; uint32_t x0 = (uint32_t)RUDO_CLAMP(lroundf(px - rx), 0.0f, (float)fb->width), y0 = (uint32_t)RUDO_CLAMP(lroundf(py - ry), 0.0f, (float)fb->height), x1 = (uint32_t)RUDO_CLAMP(lroundf(px + rx), 0.0f, (float)fb->width), y1 = (uint32_t)RUDO_CLAMP(lroundf(py + ry), 0.0f, (float)fb->height), x, y; if (p[i].shape == RUDO_CURSOR_PARTICLE_FILLED_RECT) { for (y = y0; y < y1; ++y) for (x = x0; x < x1; ++x) blend_bgra(fb, x, y, cc, p[i].alpha); } else { for (y = y0; y < y1; ++y) for (x = x0; x < x1; ++x) { float nx = rx > 0.0f ? (((float)x + 0.5f) - px) / rx : 0.0f, ny = ry > 0.0f ? (((float)y + 0.5f) - py) / ry : 0.0f, d = nx * nx + ny * ny; if (p[i].shape == RUDO_CURSOR_PARTICLE_FILLED_OVAL && d <= 1.0f) blend_bgra(fb, x, y, cc, p[i].alpha); else if (p[i].shape == RUDO_CURSOR_PARTICLE_STROKED_OVAL && d <= 1.0f && d >= RUDO_MAX(0.0f, 1.0f - p[i].stroke_width * 2.0f)) blend_bgra(fb, x, y, cc, p[i].alpha); else if (p[i].shape == RUDO_CURSOR_PARTICLE_STROKED_RECT) { uint32_t sw = (uint32_t)RUDO_MAX(1.0f, p[i].stroke_width * r->cell_height); if (x < x0 + sw || x + sw >= x1 || y < y0 + sw || y + sw >= y1) blend_bgra(fb, x, y, cc, p[i].alpha); } } } } free(p); }
static bool row_in_dirty_ranges(size_t row, const rudo_render_row_range *ranges, size_t range_count) { size_t i; if (!ranges || !range_count) return false; for (i = 0; i < range_count; ++i) if (ranges[i].start_row <= row && row <= ranges[i].end_row_inclusive) return true; return false; }

rudo_software_renderer *rudo_software_renderer_new(float font_size, const char *font_family, const rudo_theme_colors *theme, uint32_t padding) { rudo_software_renderer *r = (rudo_software_renderer *)calloc(1, sizeof(*r)); if (!r) return NULL; r->font_size = font_size > 1.0f ? font_size : 1.0f; r->base_font_size = r->font_size; r->scale = 1.0f; r->padding = padding; r->background_alpha = 255; r->font_family = rudo_strdup(font_family ? font_family : RUDO_DEFAULT_FONT_FAMILY); if (theme) r->theme = *theme; else { r->theme.foreground[0] = 0xd4; r->theme.foreground[1] = 0xd4; r->theme.foreground[2] = 0xd4; r->theme.background[0] = 0x1e; r->theme.background[1] = 0x1e; r->theme.background[2] = 0x1e; r->theme.cursor[0] = 0xff; r->theme.cursor[1] = 0xff; r->theme.cursor[2] = 0xff; r->theme.selection[0] = 0x26; r->theme.selection[1] = 0x4f; r->theme.selection[2] = 0x78; } r->font = rudo_font_atlas_new(font_size_in_pixels(r->font_size, 1.0f), r->font_family); if (!r->font) { free(r->font_family); free(r); return NULL; } r->cell_width = RUDO_MAX(rudo_font_atlas_cell_width(r->font), 1.0f); r->cell_height = RUDO_MAX(rudo_font_atlas_cell_height(r->font), 1.0f); r->baseline = rudo_font_atlas_baseline(r->font); return r; }
void rudo_software_renderer_free(rudo_software_renderer *r) { if (!r) return; rudo_font_atlas_free(r->font); free(r->font_family); free(r->col_boundaries); free(r->row_boundaries); free(r); }
void rudo_software_renderer_set_theme(rudo_software_renderer *r, const rudo_theme_colors *theme) { if (r && theme) r->theme = *theme; }
void rudo_software_renderer_set_scale(rudo_software_renderer *r, float scale) { if (!r) return; scale = scale > 1.0f ? scale : 1.0f; if (fabsf(r->scale - scale) < FLOAT_CHANGE_EPSILON) return; r->scale = scale; rebuild_font(r); }
void rudo_software_renderer_set_font_size(rudo_software_renderer *r, float font_size) { if (!r) return; font_size = font_size > 1.0f ? font_size : 1.0f; if (fabsf(r->font_size - font_size) < FLT_EPSILON) return; r->font_size = font_size; rebuild_font(r); }
void rudo_software_renderer_increase_font_size(rudo_software_renderer *r, float delta_points) { if (!r) return; if (delta_points < 0.0f) delta_points = 0.0f; rudo_software_renderer_set_font_size(r, r->font_size + delta_points); }
void rudo_software_renderer_decrease_font_size(rudo_software_renderer *r, float delta_points) { if (!r) return; if (delta_points < 0.0f) delta_points = 0.0f; rudo_software_renderer_set_font_size(r, RUDO_MAX(1.0f, r->font_size - delta_points)); }
void rudo_software_renderer_reset_font_size(rudo_software_renderer *r) { if (r) rudo_software_renderer_set_font_size(r, r->base_font_size); }
void rudo_software_renderer_set_background_alpha(rudo_software_renderer *r, uint8_t alpha) { if (r) r->background_alpha = alpha; }
void rudo_software_renderer_cell_size(const rudo_software_renderer *r, float *cell_width, float *cell_height) { if (!r) return; if (cell_width) *cell_width = r->cell_width; if (cell_height) *cell_height = r->cell_height; }
void rudo_software_renderer_grid_offset(const rudo_software_renderer *r, float *offset_x, float *offset_y) { if (!r) return; if (offset_x) *offset_x = r->offset_x; if (offset_y) *offset_y = r->offset_y; }
void rudo_software_renderer_grid_layout(rudo_software_renderer *r, uint32_t width, uint32_t height, size_t *cols, size_t *rows) { size_t c, rw; if (!r) return; anchored_grid_layout(width, height, r->cell_width, r->cell_height, r->padding, r->scale, &c, &rw, &r->offset_x, &r->offset_y); ensure_bounds(r, c, rw); if (cols) *cols = c; if (rows) *rows = rw; }
void rudo_software_renderer_window_size_for_grid(const rudo_software_renderer *r, size_t cols, size_t rows, uint32_t *width, uint32_t *height) { float phys_pad; uint32_t w, h; if (!r) return; phys_pad = (float)r->padding * r->scale; w = pixel_boundary(phys_pad, r->cell_width, cols) + (uint32_t)RUDO_MAX(lroundf(phys_pad), 0); h = pixel_boundary(phys_pad, r->cell_height, rows) + (uint32_t)RUDO_MAX(lroundf(phys_pad), 0); if (width) *width = RUDO_MAX(w, 1u); if (height) *height = RUDO_MAX(h, 1u); }
void rudo_software_renderer_pixel_bounds_for_row_range(const rudo_software_renderer *r, size_t start_row, size_t end_row_inclusive, uint32_t *y0, uint32_t *y1) { uint32_t a = 0, b = 0; if (!r || start_row > end_row_inclusive || end_row_inclusive + 1u > r->rows) return; a = r->row_boundaries[start_row]; b = r->row_boundaries[end_row_inclusive + 1u]; if (y0) *y0 = a; if (y1) *y1 = b > a ? b : a; }
void rudo_software_renderer_render(rudo_software_renderer *r, rudo_framebuffer *fb, const rudo_render_grid *grid, const rudo_cursor_renderer *cursor, rudo_render_options options) { size_t row, col; rudo_rgb background = { r->theme.background[0], r->theme.background[1], r->theme.background[2] }, foreground_theme = { r->theme.foreground[0], r->theme.foreground[1], r->theme.foreground[2] }, cursor_color = { r->theme.cursor[0], r->theme.cursor[1], r->theme.cursor[2] }, selection_bg = { r->theme.selection[0], r->theme.selection[1], r->theme.selection[2] }; size_t selection_start_row = 0, selection_end_row = 0, selection_start_col = 0, selection_end_col = 0; if (!r || !fb || !grid) return; if (r->cols != grid->cols || r->rows != grid->rows) ensure_bounds(r, grid->cols, grid->rows); if (options.full_redraw) fill_rect_raw_alpha_overwrite(fb, (rect){ 0, 0, fb->width, fb->height }, background, r->background_alpha); else if (options.dirty_rows && options.dirty_row_count) { size_t i; for (i = 0; i < options.dirty_row_count; ++i) { size_t start = options.dirty_rows[i].start_row, end = options.dirty_rows[i].end_row_inclusive; uint32_t y0, y1; if (start > end || end >= grid->rows) continue; y0 = r->row_boundaries[start]; y1 = r->row_boundaries[end + 1u]; if (y1 > y0) fill_rect_raw_alpha_overwrite(fb, (rect){ 0, y0, fb->width, y1 - y0 }, background, r->background_alpha); } }
    if (grid->has_selection) { selection_start_row = grid->selection_start_row; selection_end_row = grid->selection_end_row; selection_start_col = grid->selection_start_col; selection_end_col = grid->selection_end_col; if (selection_start_row > selection_end_row || (selection_start_row == selection_end_row && selection_start_col > selection_end_col)) { size_t tmp_row = selection_start_row, tmp_col = selection_start_col; selection_start_row = selection_end_row; selection_start_col = selection_end_col; selection_end_row = tmp_row; selection_end_col = tmp_col; } }
    for (row = 0; row < grid->rows; ++row) { size_t row_selection_start = SIZE_MAX, row_selection_end = 0; uint32_t y0 = r->row_boundaries[row], y1 = r->row_boundaries[row + 1], cell_h = y1 - y0; bool draw_row = options.full_redraw || row_in_dirty_ranges(row, options.dirty_rows, options.dirty_row_count); if (!draw_row) continue; if (grid->has_selection && row >= selection_start_row && row <= selection_end_row) { if (selection_start_row == selection_end_row) { row_selection_start = selection_start_col; row_selection_end = selection_end_col; } else if (row == selection_start_row) { row_selection_start = selection_start_col; row_selection_end = SIZE_MAX; } else if (row == selection_end_row) { row_selection_start = 0; row_selection_end = selection_end_col; } else { row_selection_start = 0; row_selection_end = SIZE_MAX; } } for (col = 0; col < grid->cols; ++col) { const rudo_render_cell *cell = &grid->cells[row * grid->cols + col]; uint32_t x0 = r->col_boundaries[col], x1 = r->col_boundaries[col + 1], cell_w = x1 - x0; rudo_rgb fg = cell->fg_default ? foreground_theme : rgb_from_u32(cell->fg), bg = cell->bg_default ? background : rgb_from_u32(cell->bg); if (cell->flags & RUDO_CELL_FLAG_REVERSE) { rudo_rgb t = fg; fg = bg; bg = t; } if (cell->flags & RUDO_CELL_FLAG_DIM) { fg.r >>= 1; fg.g >>= 1; fg.b >>= 1; } if (row_selection_start <= row_selection_end && col >= row_selection_start && col <= row_selection_end) bg = selection_bg; if (bg.r != background.r || bg.g != background.g || bg.b != background.b) fill_rect_raw_alpha_overwrite(fb, (rect){ x0, y0, cell_w, cell_h }, bg, r->background_alpha); if (cell->ch != ' ' && !(cell->flags & RUDO_CELL_FLAG_HIDDEN) && !(cell->flags & RUDO_CELL_FLAG_WIDE_SPACER)) draw_glyph(r, fb, x0, y0, cell_w, cell_h, cell->ch, fg, !!(cell->flags & RUDO_CELL_FLAG_BOLD), !!(cell->flags & RUDO_CELL_FLAG_ITALIC), NULL); if (cell->flags & RUDO_CELL_FLAG_UNDERLINE) fill_rect_raw(fb, (rect){ x0, y0 + cell_h - 1u, cell_w, 1u }, fg); if (cell->flags & RUDO_CELL_FLAG_STRIKETHROUGH) fill_rect_raw(fb, (rect){ x0, y0 + cell_h / 2u, cell_w, 1u }, fg); } }

    if (options.draw_cursor && cursor && !grid->viewing_scrollback && grid->cursor_visible && rudo_cursor_renderer_is_visible(cursor)) { float corners[8], q[8], alpha = rudo_cursor_renderer_blink_opacity(cursor); uint8_t a = (uint8_t)RUDO_CLAMP(lroundf(alpha * 255.0f), 0.0f, 255.0f); size_t ccol = RUDO_MIN(grid->cursor_col, grid->cols ? grid->cols - 1u : 0u), crow = RUDO_MIN(grid->cursor_row, grid->rows ? grid->rows - 1u : 0u); const rudo_render_cell *cell = &grid->cells[crow * grid->cols + ccol]; uint32_t cell_x = r->col_boundaries[ccol], cell_y = r->row_boundaries[crow], cell_w = r->col_boundaries[ccol + 1u] - cell_x, cell_h = r->row_boundaries[crow + 1u] - cell_y; rudo_cursor_renderer_corner_positions(cursor, corners); for (col = 0; col < 4; ++col) { q[col * 2] = r->offset_x + corners[col * 2] * r->cell_width; q[col * 2 + 1] = r->offset_y + corners[col * 2 + 1] * r->cell_height; } if (rudo_cursor_renderer_is_unfocused(cursor)) draw_unfocused_outline(fb, q, cursor_color, a, RUDO_MAX(1.0f, rudo_cursor_renderer_unfocused_outline_width(cursor) * RUDO_MIN(r->cell_width, r->cell_height))); else if (a == 255) { fill_quad(fb, q, cursor_color); draw_glyph(r, fb, cell_x, cell_y, cell_w, cell_h, cell->ch, contrasting_cursor_text_color(cursor_color), !!(cell->flags & RUDO_CELL_FLAG_BOLD), !!(cell->flags & RUDO_CELL_FLAG_ITALIC), q); } else if (a) fill_quad_alpha(fb, q, cursor_color, a); }
    if (options.draw_cursor && cursor) draw_vfx_particles(r, fb, cursor); }
